import { contextBridge, ipcRenderer } from "electron";
import type { AppApi } from "../src/shared/types";

const invoke = <T>(channel: string, ...args: unknown[]) => ipcRenderer.invoke(`studio:${channel}`, ...args) as Promise<T>;

const api: AppApi = {
  getDashboard: () => invoke("getDashboard"),
  listProjects: () => invoke("listProjects"),
  createProject: (input) => invoke("createProject", input),
  getProject: (id) => invoke("getProject", id),
  updateProject: (id, patch) => invoke("updateProject", id, patch),
  saveContract: (id, contract) => invoke("saveContract", id, contract),
  approveContract: (id) => invoke("approveContract", id),
  savePlan: (id, plan) => invoke("savePlan", id, plan),
  approvePlan: (id, planId) => invoke("approvePlan", id, planId),
  generatePlanningDraft: (id, input) => invoke("generatePlanningDraft", id, input),
  saveChapter: (id, chapter) => invoke("saveChapter", id, chapter),
  saveExpectation: (id, expectation) => invoke("saveExpectation", id, expectation),
  transitionChapter: (id, chapterId, status) => invoke("transitionChapter", id, chapterId, status),
  compileContext: (id, chapterId) => invoke("compileContext", id, chapterId),
  searchProject: (id, query) => invoke("searchProject", id, query),
  listRevisions: (id, collection, entityId) => invoke("listRevisions", id, collection, entityId),
  restoreRevision: (id, revisionId) => invoke("restoreRevision", id, revisionId),
  runQualityCheck: (id, chapterId) => invoke("runQualityCheck", id, chapterId),
  extractChapterFacts: (id, chapterId) => invoke("extractChapterFacts", id, chapterId),
  saveFact: (id, fact) => invoke("saveFact", id, fact),
  resolveIssue: (id, issueId, status) => invoke("resolveIssue", id, issueId, status),
  saveChangeRequest: (id, change) => invoke("saveChangeRequest", id, change),
  decideChangeRequest: (id, changeId, decision) => invoke("decideChangeRequest", id, changeId, decision),
  saveSchedule: (id, item) => invoke("saveSchedule", id, item),
  listRankings: () => invoke("listRankings"),
  importRankingCsv: (csvText, listName) => invoke("importRankingCsv", csvText, listName),
  capturePublicRanking: (url, listName) => invoke("capturePublicRanking", url, listName),
  listRankingSchedules: () => invoke("listRankingSchedules"),
  saveRankingSchedule: (input) => invoke("saveRankingSchedule", input),
  runRankingSchedule: (id) => invoke("runRankingSchedule", id),
  deleteRankingSchedule: (id) => invoke("deleteRankingSchedule", id),
  getRankingAnalytics: () => invoke("getRankingAnalytics"),
  listResearchBooks: () => invoke("listResearchBooks"),
  previewResearchFile: () => invoke("previewResearchFile"),
  importResearchBook: (preview, genre, rightsConfirmed, cloudConsent) => invoke("importResearchBook", preview, genre, rightsConfirmed, cloudConsent),
  listInsights: () => invoke("listInsights"),
  createInsight: (input) => invoke("createInsight", input),
  deconstructResearchBook: (bookId) => invoke("deconstructResearchBook", bookId),
  listResearchAnalyses: (bookId) => invoke("listResearchAnalyses", bookId),
  attachInsights: (id, insightIds) => invoke("attachInsights", id, insightIds),
  generateConcepts: (id) => invoke("generateConcepts", id),
  generateChapterDraft: (id, chapterId) => invoke("generateChapterDraft", id, chapterId),
  previewChapterBatch: (id, chapterId) => invoke("previewChapterBatch", id, chapterId),
  generateChapterBatch: (id, chapterId) => invoke("generateChapterBatch", id, chapterId),
  getAiSettings: () => invoke("getAiSettings"),
  saveAiSettings: (settings, apiKey) => invoke("saveAiSettings", settings, apiKey),
  exportProject: (id, format) => invoke("exportProject", id, format),
  importMetricsCsv: (id, csvText) => invoke("importMetricsCsv", id, csvText),
  getReviewSuggestions: (id) => invoke("getReviewSuggestions", id),
  createBackup: (password) => invoke("createBackup", password),
  restoreBackup: (password) => invoke("restoreBackup", password),
  getWorkspacePath: () => invoke("getWorkspacePath"),
};

contextBridge.exposeInMainWorld("novelStudio", api);
