import type { CategoryCreationPreset } from "./types";

/**
 * 每个番茄分类的开书面板推荐值。
 *
 * 只放无法从画像派生的字段：篇幅形态、视角、目标字数档、推荐开局形态/情绪基调/主角身份。
 * 单章字数、首个回报窗口、场景数、阶段数与卷数由 `src/shared/creation-presets.ts` 从画像派生，
 * 不在这里重复维护。完整性由 `tests/creation-presets.test.ts` 守住（37 个分类一一对应）。
 */
export const FANQIE_CREATION_PRESETS: Record<string, CategoryCreationPreset> = {
  // 男频
  "男频:1141": {
    lengthShape: "多卷史诗",
    narrativePerson: "第三人称限知",
    targetWords: 3_000_000,
    openingArchetypes: ["穿越", "能力觉醒"],
    toneTags: ["热血"],
    protagonistRoles: ["学生"],
  },
  "男频:1140": {
    lengthShape: "多卷史诗",
    narrativePerson: "第三人称限知",
    targetWords: 3_000_000,
    openingArchetypes: ["被逐/退婚", "继承/获得"],
    toneTags: ["热血", "冷峻"],
    protagonistRoles: [],
  },
  "男频:8": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["灾变爆发", "能力觉醒"],
    toneTags: ["悬疑紧张", "冷峻"],
    protagonistRoles: ["军人"],
  },
  "男频:261": {
    lengthShape: "日常经营",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["继承/获得", "日常切入"],
    toneTags: ["轻松", "治愈"],
    protagonistRoles: ["店主/创业者"],
  },
  "男频:124": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["能力觉醒", "系统降临"],
    toneTags: ["热血"],
    protagonistRoles: ["学生"],
  },
  "男频:1014": {
    lengthShape: "长线连续",
    narrativePerson: "多视角切换",
    targetWords: 1_500_000,
    openingArchetypes: ["能力觉醒"],
    toneTags: ["热血", "冷峻"],
    protagonistRoles: ["学生"],
  },
  "男频:273": {
    lengthShape: "多卷史诗",
    narrativePerson: "第三人称限知",
    targetWords: 3_000_000,
    openingArchetypes: ["穿越", "继承/获得"],
    toneTags: ["冷峻"],
    protagonistRoles: ["军人"],
  },
  "男频:27": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["被逐/退婚", "回归/重逢"],
    toneTags: ["热血"],
    protagonistRoles: ["军人"],
  },
  "男频:263": {
    lengthShape: "日常经营",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["重生", "日常切入"],
    toneTags: ["治愈"],
    protagonistRoles: ["店主/创业者"],
  },
  "男频:258": {
    lengthShape: "多卷史诗",
    narrativePerson: "第三人称限知",
    targetWords: 3_000_000,
    openingArchetypes: ["被逐/退婚", "能力觉醒"],
    toneTags: ["热血"],
    protagonistRoles: [],
  },
  "男频:272": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["穿越", "系统降临"],
    toneTags: ["轻松", "热血"],
    protagonistRoles: [],
  },
  "男频:539": {
    lengthShape: "单元剧",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["悬案介入", "失忆/身份未知"],
    toneTags: ["悬疑紧张"],
    protagonistRoles: ["警察/调查员"],
  },
  "男频:262": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["系统降临", "能力觉醒"],
    toneTags: ["轻松", "热血"],
    protagonistRoles: ["职场新人"],
  },
  "男频:257": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["穿越", "系统降临"],
    toneTags: ["热血", "沙雕"],
    protagonistRoles: [],
  },
  "男频:751": {
    lengthShape: "单元剧",
    narrativePerson: "第一人称",
    targetWords: 1_500_000,
    openingArchetypes: ["悬案介入", "失忆/身份未知"],
    toneTags: ["悬疑紧张", "冷峻"],
    protagonistRoles: ["警察/调查员"],
  },
  "男频:504": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["悬案介入", "失忆/身份未知"],
    toneTags: ["悬疑紧张", "冷峻"],
    protagonistRoles: ["军人"],
  },
  "男频:746": {
    lengthShape: "单元剧",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["能力觉醒", "契约绑定"],
    toneTags: ["热血"],
    protagonistRoles: ["学生"],
  },
  "男频:718": {
    lengthShape: "单元剧",
    narrativePerson: "多视角切换",
    targetWords: 1_500_000,
    openingArchetypes: ["穿越", "系统降临"],
    toneTags: ["热血", "沙雕"],
    protagonistRoles: ["学生"],
  },
  "男频:1016": {
    lengthShape: "单元剧",
    narrativePerson: "多视角切换",
    targetWords: 1_500_000,
    openingArchetypes: ["穿越", "契约绑定"],
    toneTags: ["热血", "沙雕"],
    protagonistRoles: [],
  },
  // 女频
  "女频:1139": {
    lengthShape: "多卷史诗",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["穿越", "被逐/退婚"],
    toneTags: ["虐恋"],
    protagonistRoles: ["继承人"],
  },
  "女频:8": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["灾变爆发", "重生"],
    toneTags: ["悬疑紧张", "热血"],
    protagonistRoles: ["医生"],
  },
  "女频:746": {
    lengthShape: "单元剧",
    narrativePerson: "第三人称限知",
    targetWords: 1_000_000,
    openingArchetypes: ["契约绑定", "能力觉醒"],
    toneTags: ["热血", "轻松"],
    protagonistRoles: ["学生"],
  },
  "女频:1015": {
    lengthShape: "单元剧",
    narrativePerson: "多视角切换",
    targetWords: 1_000_000,
    openingArchetypes: ["穿越", "系统降临"],
    toneTags: ["甜宠", "轻松"],
    protagonistRoles: [],
  },
  "女频:248": {
    lengthShape: "多卷史诗",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["穿越", "契约绑定"],
    toneTags: ["甜宠", "虐恋"],
    protagonistRoles: [],
  },
  "女频:23": {
    lengthShape: "日常经营",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["重生", "日常切入"],
    toneTags: ["治愈", "轻松"],
    protagonistRoles: ["店主/创业者"],
  },
  "女频:79": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["重生", "回归/重逢"],
    toneTags: ["治愈", "虐恋"],
    protagonistRoles: ["店主/创业者"],
  },
  "女频:267": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_000_000,
    openingArchetypes: ["系统降临", "继承/获得"],
    toneTags: ["甜宠", "轻松"],
    protagonistRoles: ["职场新人"],
  },
  "女频:246": {
    lengthShape: "多卷史诗",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["重生", "被逐/退婚"],
    toneTags: ["虐恋", "冷峻"],
    protagonistRoles: ["继承人"],
  },
  "女频:539": {
    lengthShape: "单元剧",
    narrativePerson: "第一人称",
    targetWords: 1_000_000,
    openingArchetypes: ["悬案介入", "失忆/身份未知"],
    toneTags: ["悬疑紧张"],
    protagonistRoles: ["警察/调查员"],
  },
  "女频:253": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["重生", "穿越"],
    toneTags: ["虐恋", "冷峻"],
    protagonistRoles: ["继承人"],
  },
  "女频:24": {
    lengthShape: "单元剧",
    narrativePerson: "第一人称",
    targetWords: 1_500_000,
    openingArchetypes: ["穿越", "系统降临"],
    toneTags: ["甜宠", "轻松"],
    protagonistRoles: [],
  },
  "女频:749": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_000_000,
    openingArchetypes: ["日常切入", "回归/重逢"],
    toneTags: ["甜宠", "治愈"],
    protagonistRoles: ["学生"],
  },
  "女频:745": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_000_000,
    openingArchetypes: ["继承/获得", "回归/重逢"],
    toneTags: ["甜宠", "热血"],
    protagonistRoles: ["艺人/主播"],
  },
  "女频:747": {
    lengthShape: "单元剧",
    narrativePerson: "第一人称",
    targetWords: 1_000_000,
    openingArchetypes: ["悬案介入"],
    toneTags: ["悬疑紧张", "冷峻"],
    protagonistRoles: ["警察/调查员"],
  },
  "女频:750": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_000_000,
    openingArchetypes: ["契约绑定", "日常切入"],
    toneTags: ["甜宠", "轻松"],
    protagonistRoles: ["职场新人"],
  },
  "女频:748": {
    lengthShape: "长线连续",
    narrativePerson: "第三人称限知",
    targetWords: 1_000_000,
    openingArchetypes: ["契约绑定", "继承/获得"],
    toneTags: ["甜宠", "虐恋"],
    protagonistRoles: ["继承人"],
  },
  "女频:1017": {
    lengthShape: "多卷史诗",
    narrativePerson: "第三人称限知",
    targetWords: 1_500_000,
    openingArchetypes: ["回归/重逢", "契约绑定"],
    toneTags: ["虐恋", "冷峻"],
    protagonistRoles: ["医生"],
  },
};
