import type { FanqieCategoryProfile } from "./types";
import { FANQIE_PROFILE_VERSION } from "./types";

export const FEMALE_CATEGORY_PROFILES: FanqieCategoryProfile[] = [
  {
    key: "女频:1139",
    channel: "女频",
    categoryId: "1139",
    name: "古风世情",
    genre: "古言宅斗",
    recommendedSubtype: "婚恋权谋",
    coreFantasy: "古代身份、情感和家国选择",
    audience: "偏好情感牵引与时代命运",
    openingFocus: "先落下婚姻/家族压力和一个不可退让的目标",
    taboo: "只有宅斗技巧没有情感代价",
    conflictEngine: '让"想守的人"和"必须守的家族/名声"互相撕扯——每次选择都要牺牲一处情感或体面。',
    payoffPattern: "第 1–3 章给一次局部脱困，第 10–20 章给一次身份或婚约转机，卷末兑现家族或朝局级回报。",
    expansionAxis: "内宅关系 → 家族与姻亲 → 朝局与家国 → 个人选择定型",
    fatigueSignal: "连续两轮只靠内宅算计，或情感线停滞只走事件。",
    qualityChecks: [
      "本章的算计是否付出了情感代价？",
      "关系是否发生了不可逆变化？",
      "家国背景是否真实影响选择？",
      "是否触发禁忌：只有宅斗技巧没有情感代价？",
    ],
    narrativeGenres: ["权谋", "恋爱"],
    genreElements: ["古代", "宫廷", "家族"],
    expansionRoutes: ["内宅脱困", "家族与姻亲博弈", "朝局与家国抉择", "人物关系定型"],
    tags: ["古言", "宅斗", "权谋", "婚恋", "世家", "宫廷", "家国", "情感"],
    siblingCategories: ["女频:246", "女频:253"],
    readerAgeBand: "18–40 岁，偏好情感与权谋并重",
    chapterHookStyle: "首章同时给出婚约/家族压力与主角不肯退让的底线",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 4–6 章一次关系或处境回报，每卷末一次家族级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["替嫁", "重生回婚约前", "家族落难"],
    clicheTraps: ["算计堆砌无情感", "反派降智", "时代背景当摆设"],
    differentiationAngles: ["每次选择都有情感成本", "让配角有独立立场", "家国线与情感线互相推动"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:8",
    channel: "女频",
    categoryId: "8",
    name: "科幻末世",
    genre: "科幻末世",
    recommendedSubtype: "异能规则",
    coreFantasy: "灾变环境中的生存、关系和资源掌控",
    audience: "偏好危机求生和女性成长",
    openingFocus: "先展示资源缺口与关系信任风险",
    taboo: "囤货清单替代人物行动",
    conflictEngine: '让"活下去"和"信谁"互相考验——每多收一个人就多一份资源压力与背叛风险。',
    payoffPattern: "第 1–3 章给一次安全落脚，第 10–20 章给一次稳定据点，卷末兑现群体中的主导位置。",
    expansionAxis: "个人求生 → 小队信任 → 据点规则 → 灾变秩序与话语权",
    fatigueSignal: "连续两轮只写物资清点，或危机只由外部怪物驱动。",
    qualityChecks: [
      "本章是否推进了生存与关系两条线？",
      "新增关系是否带来资源或信任成本？",
      "威胁是否可被规则解释？",
      "是否触发禁忌：囤货清单替代人物行动？",
    ],
    narrativeGenres: ["生存", "恋爱"],
    genreElements: ["末世", "系统", "群像"],
    expansionRoutes: ["资源缺口求生", "小队信任建立与破裂", "据点规则成形", "秩序与话语权重构"],
    tags: ["末世", "生存", "异能", "囤货", "据点", "女性成长", "群像", "危机"],
    siblingCategories: ["男频:8", "女频:24"],
    readerAgeBand: "18–35 岁，偏好危机中的关系与成长",
    chapterHookStyle: '首章用一次"救不救这个人"的资源选择开局',
    firstPayoffWindow: [1, 3],
    payoffCadence: "每 3–5 章一次生存或关系回报，每卷末一次据点级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["灾变当天觉醒", "重生回灾变前", "空间异能"],
    clicheTraps: ["囤货流水", "配角只会拖累", "怪物无规则"],
    differentiationAngles: ["把信任写成资源账", "让配角有独立能力", "威胁遵循可推演规则"],
    baselineDelta: {
      readerPromise: "灾变环境中的生存、关系与资源掌控，信任是稀缺资源",
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:746",
    channel: "女频",
    categoryId: "746",
    name: "游戏体育",
    genre: "游戏竞技",
    recommendedSubtype: "系统成长",
    coreFantasy: "竞技目标与亲密关系双线成长",
    audience: "偏好轻快节奏和关系回报",
    openingFocus: "让事业目标与关系冲突在首段相撞",
    taboo: "比赛或恋爱线沦为背景",
    conflictEngine: '让"竞技目标"和"亲密关系"互相占时间——每次为比赛加练都要在关系上补一次欠账。',
    payoffPattern: "第 1–3 章给一次竞技或关系小胜，第 10–20 章给一次赛场与关系双确认，卷末兑现职业位置。",
    expansionAxis: "个人技术 → 队伍与搭档 → 联赛与公众关注 → 职业与关系定型",
    fatigueSignal: "连续两轮只有比赛没有关系变化，或关系线不影响竞技选择。",
    qualityChecks: [
      "本章竞技与关系是否互相影响？",
      "关系推进是否由具体行动促成？",
      "对手或队友是否有独立目标？",
      "是否触发禁忌：比赛或恋爱线沦为背景？",
    ],
    narrativeGenres: ["竞技", "恋爱"],
    genreElements: ["校园", "职场", "双强"],
    expansionRoutes: ["短板训练验证", "搭档关系成形", "联赛与舆论压力", "职业与关系定型"],
    tags: ["竞技", "电竞", "体育", "恋爱", "搭档", "联赛", "青春", "成长"],
    siblingCategories: ["男频:746", "女频:749"],
    readerAgeBand: "16–30 岁，偏好轻快与双线成长",
    chapterHookStyle: "首章让比赛目标和关系冲突同时出现",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次竞技或关系回报，每卷末一次联赛级回报",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["被队里排挤", "临时替补", "旧搭档回归"],
    clicheTraps: ["比赛略写", "恋爱线脱离竞技", "对手只会挑衅"],
    differentiationAngles: ["让两条线互相牵制", "比赛过程写完整", "关系靠行动推进"],
    baselineDelta: {
      readerPromise: "竞技目标与亲密关系双线成长，两条线互相牵制",
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:1015",
    channel: "女频",
    categoryId: "1015",
    name: "女频衍生",
    genre: "快穿衍生",
    recommendedSubtype: "破镜重圆",
    coreFantasy: "熟悉世界中的女性主体关系与新选择",
    audience: "偏好代入感和情感新鲜度",
    openingFocus: "先给原创女主的独立欲望和关系缺口",
    taboo: "复述原作或只靠角色名",
    conflictEngine: '让"熟悉关系"和"原创选择"互相较劲——每次借用原作关系都要让女主付出一部分自主权。',
    payoffPattern: "第 1–3 章给一次女主独立行动成功，第 10–20 章给一次关系重定义，卷末兑现原创主线成立。",
    expansionAxis: "个人欲望 → 原创关系 → 与原作格局的碰撞 → 新关系秩序",
    fatigueSignal: "连续两轮靠原作角色推动，或女主只做旁观者。",
    qualityChecks: [
      "本章是否由女主主动推动？",
      "关系变化是否来自原创选择？",
      "是否避免复述原作？",
      "是否触发禁忌：复述原作或只靠角色名？",
    ],
    narrativeGenres: ["恋爱", "群像"],
    genreElements: ["现代都市", "群像", "破镜重圆"],
    expansionRoutes: ["独立欲望确立", "原创关系成形", "与原作格局碰撞", "新关系秩序"],
    tags: ["衍生", "同人", "原创女主", "关系", "群像", "情感", "成长", "代入"],
    siblingCategories: ["男频:1016", "女频:267"],
    readerAgeBand: "16–30 岁，偏好熟悉世界中的新关系",
    chapterHookStyle: "首章给出女主的独立欲望和一处关系缺口",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次关系或立足回报，每卷末一次格局级回报",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["穿越进熟悉故事", "成为原作配角", "重生改变关系"],
    clicheTraps: ["复述原作", "女主工具化", "只靠角色名吸引"],
    differentiationAngles: ["女主有独立目标", "关系由行动改变", "原作只做背景"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:248",
    channel: "女频",
    categoryId: "248",
    name: "玄幻言情",
    genre: "玄幻/仙侠",
    recommendedSubtype: "宗门升级",
    coreFantasy: "高概念世界中的情感羁绊和力量成长",
    audience: "偏好强设定与情感回报",
    openingFocus: "用世界规则压力逼迫两人共同选择",
    taboo: "感情线脱离世界危机",
    conflictEngine: '让"修炼/阵营选择"和"两个人的关系"互相绑定——每次力量或立场变化都会重新定义两人能站多近。',
    payoffPattern: "第 1–3 章给一次共同脱险，第 10–20 章给一次关系与境界双突破，卷末兑现阵营或道侣级回报。",
    expansionAxis: "个人修炼 → 双人羁绊 → 阵营与规则冲突 → 共同选择的终局",
    fatigueSignal: "连续两轮只有感情没有世界压力，或危机不影响两人关系。",
    qualityChecks: [
      "本章的世界危机是否改变了两人关系？",
      "力量成长是否带来关系代价？",
      "两人是否有各自目标？",
      "是否触发禁忌：感情线脱离世界危机？",
    ],
    narrativeGenres: ["恋爱", "成长"],
    genreElements: ["修仙界", "异世界", "双强"],
    expansionRoutes: ["共同脱险", "羁绊与境界同步", "阵营与规则冲突", "终局共同选择"],
    tags: ["玄幻", "言情", "修仙", "道侣", "双强", "阵营", "情感", "成长"],
    siblingCategories: ["女频:23", "男频:1140"],
    readerAgeBand: "18–35 岁，偏好强设定与情感张力",
    chapterHookStyle: "首章用一次世界规则迫使两人必须共同做的选择开局",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 4–6 章一次关系或境界回报，每卷末一次阵营级回报",
    typicalChapterWords: [2200, 3000],
    commonOpenings: ["被迫结契", "同门对立", "阵营敌对"],
    clicheTraps: ["感情脱离世界", "男主万能", "危机只做背景"],
    differentiationAngles: ["世界规则决定关系边界", "力量成长改变关系位置", "两人各有独立目标"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:23",
    channel: "女频",
    categoryId: "23",
    name: "种田",
    genre: "年代重生",
    recommendedSubtype: "创业致富",
    coreFantasy: "从家庭/资源困境到稳定生活与关系改善",
    audience: "偏好经营、家庭和持续回报",
    openingFocus: "用一个马上会造成损失的生活难题开局",
    taboo: "只罗列生产流程",
    conflictEngine: '让"改善生活"和"家庭关系"互相牵制——每改善一处条件，都会改变家里原有的权力与情感格局。',
    payoffPattern: "第 1–3 章给一次生活改善，第 10–20 章给一次产业或家庭地位变化，卷末兑现家族与村庄级影响。",
    expansionAxis: "家庭生活 → 生产与销售 → 村庄与集体 → 时代机会",
    fatigueSignal: "连续两轮只写生产流程和收入数字。",
    qualityChecks: [
      "本章的改善是否改变了家庭关系？",
      "生产细节是否服务于人物选择？",
      "是否出现新的现实约束？",
      "是否触发禁忌：只罗列生产流程？",
    ],
    narrativeGenres: ["经营", "恋爱"],
    genreElements: ["年代", "乡村", "家族"],
    expansionRoutes: ["家庭生活改善", "生产与销售成形", "村庄与集体关系", "时代机会把握"],
    tags: ["种田", "年代", "乡村", "家庭", "创业", "经营", "温情", "成长"],
    siblingCategories: ["女频:79", "男频:263"],
    readerAgeBand: "25–45 岁，偏好生活细节与稳定回报",
    chapterHookStyle: '用一个"这周不解决就断粮/亏钱"的生活难题开局',
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次生活或经营回报，每卷末一次村庄级回报",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["重生回困难年代", "嫁进穷家", "接手破摊子"],
    clicheTraps: ["生产流水账", "亲戚脸谱化", "时代政策失真"],
    differentiationAngles: ["每次改善都改关系", "把政策与资源约束写实", "让配角有真实动机"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:79",
    channel: "女频",
    categoryId: "79",
    name: "年代",
    genre: "年代重生",
    recommendedSubtype: "创业致富",
    coreFantasy: "时代机会、家庭关系和个人重启",
    audience: "偏好时代代入和命运修正",
    openingFocus: "把前世遗憾与当下政策/资源机会绑定",
    taboo: "现代知识无视时代政策",
    conflictEngine: '让"抓住机会"和"时代政策/家庭阻力"互相顶——每个机会窗口都要先解决合规与家人反对。',
    payoffPattern: "第 1–3 章给一次小机会兑现，第 10–20 章给一次事业成形，卷末兑现家庭与地方级影响。",
    expansionAxis: "个人机会 → 家庭与亲友 → 地方与政策 → 时代浪潮中的位置",
    fatigueSignal: "连续两轮靠现代知识碾压，或政策只做背景。",
    qualityChecks: [
      "本章的机会是否受时代政策限制？",
      "家人反对是否有合理动机？",
      "是否有人因主角的选择改变立场？",
      "是否触发禁忌：现代知识无视时代政策？",
    ],
    narrativeGenres: ["经营", "群像"],
    genreElements: ["年代", "职场", "家族"],
    expansionRoutes: ["机会验证", "家庭与亲友关系", "地方与政策博弈", "时代浪潮定位"],
    tags: ["年代", "重生", "创业", "家庭", "政策", "经营", "温情", "逆袭"],
    siblingCategories: ["女频:23", "男频:272"],
    readerAgeBand: "25–45 岁，偏好时代代入与命运修正",
    chapterHookStyle: "首章把前世遗憾与当下一个具体机会绑定",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 4–6 章一次事业或家庭回报，每卷末一次地方级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["重生回高考/招工前", "返城", "接手家里生意"],
    clicheTraps: ["知识碾压时代", "政策失真", "亲戚集体刻薄"],
    differentiationAngles: ["把政策成本写实", "家人立场有理由", "机会窗口有时限"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:267",
    channel: "女频",
    categoryId: "267",
    name: "现言脑洞",
    genre: "现言甜宠",
    recommendedSubtype: "先婚后爱",
    coreFantasy: "现实关系中的身份反差和情感确认",
    audience: "偏好强钩子与高密度情绪反馈",
    openingFocus: "首章让契约关系立刻产生现实后果",
    taboo: "误会循环和纯撒糖",
    conflictEngine: '让"契约条件"和"真实情感"互相拉扯——每次靠近都要先处理一条契约或身份上的现实问题。',
    payoffPattern: "第 1–3 章给一次关系破冰，第 10–20 章给一次身份或契约转折，卷末兑现关系确认。",
    expansionAxis: "契约关系 → 家庭与职场 → 身份与旧关系 → 关系定型",
    fatigueSignal: "连续两轮靠误会推进，或情绪反馈不改变现实关系。",
    qualityChecks: [
      "本章的关系推进是否来自具体行动？",
      "契约/身份条件是否产生现实后果？",
      "是否有新的人物立场出现？",
      "是否触发禁忌：误会循环和纯撒糖？",
    ],
    narrativeGenres: ["恋爱", "群像"],
    genreElements: ["现代都市", "契约关系", "职场"],
    expansionRoutes: ["契约边界试探", "家庭与职场介入", "身份与旧关系清算", "关系定型"],
    tags: ["现言", "脑洞", "先婚后爱", "契约", "身份反差", "甜宠", "都市", "情感"],
    siblingCategories: ["女频:748", "女频:1015"],
    readerAgeBand: "18–35 岁，偏好强钩子与情绪密度",
    chapterHookStyle: "首章让契约关系立刻产生一个现实后果",
    firstPayoffWindow: [1, 3],
    payoffCadence: "每 2–4 章一次关系回报，每卷末一次关系阶段级回报",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["协议结婚", "替嫁", "同居契约"],
    clicheTraps: ["误会循环", "撒糖无剧情", "男主全能"],
    differentiationAngles: ["契约条款写清楚", "每次靠近都有代价", "配角有独立利益"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:246",
    channel: "女频",
    categoryId: "246",
    name: "宫斗宅斗",
    genre: "古言宅斗",
    recommendedSubtype: "家宅经营",
    coreFantasy: "家族资源、名声与亲密关系的博弈",
    audience: "偏好证据链、反转和情感代价",
    openingFocus: "给出一个可验证的家宅危机与有限资源",
    taboo: "靠降智反派推进",
    conflictEngine: '让"争资源"和"保关系"互相冲突——每次赢下一局都要在信任或名声上付一次账。',
    payoffPattern: "第 1–3 章给一次证据翻盘，第 10–20 章给一次掌家或婚配转机，卷末兑现家族地位。",
    expansionAxis: "内宅证据 → 家族资源 → 姻亲与外部势力 → 家宅秩序定型",
    fatigueSignal: "连续两轮靠反派失误取胜，或证据链跳过推理。",
    qualityChecks: [
      "本章的胜负是否来自可复核的证据链？",
      "反派是否有合理动机与手段？",
      "主角是否付出了关系代价？",
      "是否触发禁忌：靠降智反派推进？",
    ],
    narrativeGenres: ["权谋", "群像"],
    genreElements: ["古代", "宫廷", "家族"],
    expansionRoutes: ["证据链积累", "家族资源重组", "姻亲与外部势力", "家宅秩序定型"],
    tags: ["宫斗", "宅斗", "古言", "权谋", "证据", "家族", "反转", "女性成长"],
    siblingCategories: ["女频:1139", "女频:253"],
    readerAgeBand: "18–40 岁，偏好智斗与反转",
    chapterHookStyle: "首章给出一个可验证的家宅危机和有限资源",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次证据或地位回报，每卷末一次家族级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["被诬陷", "嫁入高门", "重生回关键节点"],
    clicheTraps: ["反派降智", "证据凭空出现", "主角无代价"],
    differentiationAngles: ["证据链可回溯", "反派手段专业", "每次赢都有关系损失"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:539",
    channel: "女频",
    categoryId: "539",
    name: "悬疑脑洞",
    genre: "悬疑推理",
    recommendedSubtype: "异能规则",
    coreFantasy: "关系与真相在日常异常中逐层揭开",
    audience: "偏好悬念和情感绑定",
    openingFocus: "先给异常证据再给人物选择",
    taboo: "反转只靠隐瞒信息",
    conflictEngine: '让"查真相"和"维护关系"互相为难——每查一层都可能把亲近的人变成嫌疑人。',
    payoffPattern: "第 1–3 章给一次线索闭环，第 10–20 章给一次关系与真相的双重揭露，卷末兑现主线一层。",
    expansionAxis: "日常异常 → 关系疑点 → 案件关联 → 真相与关系摊牌",
    fatigueSignal: "连续两轮靠新角色口述信息，或反转无前置线索。",
    qualityChecks: [
      "本章线索是否此前出现过？",
      "关系疑点是否由行动产生？",
      "读者信息量是否真的增加？",
      "是否触发禁忌：反转只靠隐瞒信息？",
    ],
    narrativeGenres: ["悬疑", "恋爱"],
    genreElements: ["现代都市", "探案", "家族"],
    expansionRoutes: ["异常证据积累", "关系疑点推进", "案件关联成形", "真相与关系摊牌"],
    tags: ["悬疑", "脑洞", "推理", "关系", "日常", "反转", "情感", "探案"],
    siblingCategories: ["男频:539", "女频:747"],
    readerAgeBand: "18–35 岁，偏好悬念与情感绑定",
    chapterHookStyle: "首章先给异常证据，再让主角做一次涉及亲近关系的选择",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次线索回报，每卷末一次主线真相推进",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["身边人行为异常", "收到旧物", "搬进新家"],
    clicheTraps: ["隐瞒信息式反转", "配角口述真相", "规则随时改"],
    differentiationAngles: ["所有反转前置线索", "调查伤及关系", "真相改变人物立场"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:253",
    channel: "女频",
    categoryId: "253",
    name: "古言脑洞",
    genre: "古言宅斗",
    recommendedSubtype: "复仇逆袭",
    coreFantasy: "古代规则漏洞与女性主体性反击",
    audience: "偏好智斗、反转和身份成长",
    openingFocus: "首章明确旧债、证据和反击目标",
    taboo: "复仇清单化导致人物扁平",
    conflictEngine: '让"复仇目标"和"自我选择"互相冲突——每推进一次复仇都要重新回答"我要成为什么样的人"。',
    payoffPattern: "第 1–3 章给一次反击得手，第 10–20 章给一次身份或婚配主动，卷末兑现旧债清算。",
    expansionAxis: "旧债证据 → 家族与姻亲 → 朝局与制度 → 自我选择定型",
    fatigueSignal: "连续两轮只完成复仇清单，或主角手段与目标不再冲突。",
    qualityChecks: [
      "本章的复仇是否付出了关系或自我认同代价？",
      "对手是否有合理防御？",
      "主角的立场是否发生变化？",
      "是否触发禁忌：复仇清单化？",
    ],
    narrativeGenres: ["复仇", "权谋"],
    genreElements: ["古代", "宫廷", "家族"],
    expansionRoutes: ["旧债证据积累", "家族与姻亲博弈", "朝局与制度利用", "自我选择定型"],
    tags: ["古言", "脑洞", "复仇", "逆袭", "智斗", "宫廷", "女性成长", "反转"],
    siblingCategories: ["女频:1139", "女频:246"],
    readerAgeBand: "18–40 岁，偏好智斗与主体性成长",
    chapterHookStyle: "首章明确旧债、第一份证据和反击目标",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次反击回报，每卷末一次旧债清算级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["重生复仇", "被陷害后归来", "替身反杀"],
    clicheTraps: ["复仇清单化", "反派排队送", "主角手段无代价"],
    differentiationAngles: ["每步复仇都改变主角", "对手会反制", "终点是自我选择而非单纯清算"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:24",
    channel: "女频",
    categoryId: "24",
    name: "快穿",
    genre: "快穿衍生",
    recommendedSubtype: "异能规则",
    coreFantasy: "多世界任务中的关系修复与自我确认",
    audience: "偏好高密度单元回报和长线谜团",
    openingFocus: "单元首章同时明确任务和情感缺口",
    taboo: "任务模板重复且主线停滞",
    conflictEngine: '让"完成单元任务"和"守住自我"互相拉扯——每次代入新身份都会模糊一点自己的立场。',
    payoffPattern: "每个单元给一次任务闭环，每 3–5 个单元推进一次主线谜团，卷末兑现自我认同。",
    expansionAxis: "单元任务 → 单元关系 → 主线组织与身份 → 自我与规则来源",
    fatigueSignal: "连续两个单元结构雷同，或主线长期不推进。",
    qualityChecks: [
      "本章单元是否有独立的冲突与回报？",
      "主线是否推进了一点？",
      "主角的自我认知是否变化？",
      "是否触发禁忌：任务模板重复且主线停滞？",
    ],
    narrativeGenres: ["冒险", "群像"],
    genreElements: ["无限流", "群像", "系统"],
    expansionRoutes: ["单元任务闭环", "单元关系积累", "主线组织显形", "自我与规则来源"],
    tags: ["快穿", "无限流", "单元", "系统", "任务", "群像", "情感", "成长"],
    siblingCategories: ["女频:8", "男频:262"],
    readerAgeBand: "16–32 岁，偏好单元回报与长线谜团",
    chapterHookStyle: "单元首章同时给出任务目标和一个具体情感缺口",
    firstPayoffWindow: [1, 3],
    payoffCadence: "每单元一次闭环，每 3–5 单元一次主线推进",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["绑定系统做任务", "穿越不同身份", "修复遗憾"],
    clicheTraps: ["单元模板重复", "主线停滞", "主角无自我"],
    differentiationAngles: ["每个单元换一种冲突结构", "主线持续给新信息", "自我认同是真正赌注"],
    baselineDelta: {
      readerPromise: "多世界任务中的关系修复与自我确认，单元回报与主线谜团并行",
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:749",
    channel: "女频",
    categoryId: "749",
    name: "青春甜宠",
    genre: "青春校园",
    recommendedSubtype: "职场恋爱",
    coreFantasy: "成长阶段的陪伴、选择和关系确认",
    audience: "偏好轻松情绪和人物成长",
    openingFocus: "用具体成长目标制造关系靠近与阻碍",
    taboo: "只有暧昧没有行动",
    conflictEngine: '让"个人成长目标"和"关系靠近"互相占时间——每次为关系让步都会拖慢自己的目标。',
    payoffPattern: "第 1–3 章给一次关系破冰，第 10–20 章给一次目标与关系双确认，卷末兑现成长与关系定型。",
    expansionAxis: "校园/初入职场 → 同伴关系 → 目标与选择 → 成长定型",
    fatigueSignal: "连续两轮只有暧昧互动，或成长目标不推进。",
    qualityChecks: [
      "本章关系推进是否由行动促成？",
      "主角的成长目标是否推进？",
      "是否有新的现实阻碍？",
      "是否触发禁忌：只有暧昧没有行动？",
    ],
    narrativeGenres: ["恋爱", "成长"],
    genreElements: ["校园", "职场", "双强"],
    expansionRoutes: ["关系破冰", "同伴关系成形", "目标与选择冲突", "成长定型"],
    tags: ["青春", "甜宠", "校园", "职场", "恋爱", "成长", "陪伴", "轻松"],
    siblingCategories: ["女频:745", "女频:746"],
    readerAgeBand: "16–28 岁，偏好轻松情绪与成长",
    chapterHookStyle: "首章用具体成长目标制造一次关系靠近与阻碍",
    firstPayoffWindow: [1, 3],
    payoffCadence: "每 2–4 章一次关系回报，每卷末一次成长阶段回报",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["同桌/室友初遇", "面试撞车", "重逢旧识"],
    clicheTraps: ["暧昧循环", "成长线停滞", "配角工具化"],
    differentiationAngles: ["关系与目标互相牵制", "每次靠近都要付行动成本", "配角有独立成长"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:745",
    channel: "女频",
    categoryId: "745",
    name: "星光璀璨",
    genre: "现实职场",
    recommendedSubtype: "职场恋爱",
    coreFantasy: "事业曝光、竞争与亲密关系共同升级",
    audience: "偏好娱乐行业反馈和情感拉扯",
    openingFocus: "首章给出事业机会与公开风险",
    taboo: "娱乐圈只写炫耀",
    conflictEngine: '让"曝光度"和"私人关系"互相牵制——每次事业上升都会让关系承受一次公众审视。',
    payoffPattern: "第 1–3 章给一次机会兑现，第 10–20 章给一次事业与关系转折，卷末兑现行业位置。",
    expansionAxis: "个人机会 → 团队与公司 → 行业竞争与舆论 → 事业与关系定型",
    fatigueSignal: "连续两轮只写红毯和热度数字，或舆论不影响人物选择。",
    qualityChecks: [
      "本章的事业进展是否带来关系压力？",
      "行业细节是否可信？",
      "竞争对手是否有专业手段？",
      "是否触发禁忌：娱乐圈只写炫耀？",
    ],
    narrativeGenres: ["恋爱", "经营"],
    genreElements: ["娱乐圈", "职场", "双强"],
    expansionRoutes: ["机会兑现", "团队与公司博弈", "舆论与竞争", "事业与关系定型"],
    tags: ["娱乐圈", "星光", "事业", "恋爱", "舆论", "竞争", "成长", "情感"],
    siblingCategories: ["女频:750", "女频:749"],
    readerAgeBand: "18–35 岁，偏好行业感与情感拉扯",
    chapterHookStyle: "首章同时给出一个事业机会和一次公开风险",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次事业或关系回报，每卷末一次行业级回报",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["替演救场", "被雪藏后翻红", "签约风波"],
    clicheTraps: ["只写炫耀", "舆论当背景", "对手无专业度"],
    differentiationAngles: ["行业规则写实", "曝光必然影响关系", "对手按行业逻辑出手"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:747",
    channel: "女频",
    categoryId: "747",
    name: "女频悬疑",
    genre: "悬疑推理",
    recommendedSubtype: "异能规则",
    coreFantasy: "关系选择与真相追索互相施压",
    audience: "偏好情感悬疑和女性视角",
    openingFocus: "先让亲密关系产生可信疑点",
    taboo: "用恋爱遮蔽案件因果",
    conflictEngine: '让"相信谁"和"查清什么"互相矛盾——每排除一个嫌疑人都会动摇一段关系。',
    payoffPattern: "第 1–3 章给一次疑点闭环，第 10–20 章给一次关系与真相双重揭露，卷末兑现主线一层。",
    expansionAxis: "亲密疑点 → 关系网 → 案件关联 → 真相与关系摊牌",
    fatigueSignal: "连续两轮只有感情戏不推进案件，或真相靠口述。",
    qualityChecks: [
      "本章案件因果是否推进？",
      "关系疑点是否由证据支撑？",
      "读者的信息量是否增加？",
      "是否触发禁忌：用恋爱遮蔽案件因果？",
    ],
    narrativeGenres: ["悬疑", "恋爱"],
    genreElements: ["现代都市", "探案", "家族"],
    expansionRoutes: ["疑点积累", "关系网排查", "案件关联成形", "真相与关系摊牌"],
    tags: ["悬疑", "女性视角", "推理", "关系", "探案", "反转", "情感", "都市"],
    siblingCategories: ["女频:539", "男频:751"],
    readerAgeBand: "18–40 岁，偏好情感悬疑",
    chapterHookStyle: "首章让一段亲密关系产生可信疑点，并给出第一份证据",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次线索回报，每卷末一次主线真相推进",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["伴侣失踪", "旧案重启", "收到匿名证据"],
    clicheTraps: ["恋爱遮蔽案件", "证据凭空出现", "反派动机单薄"],
    differentiationAngles: ["案件因果优先", "关系疑点有证据", "真相改变关系格局"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:750",
    channel: "女频",
    categoryId: "750",
    name: "职场婚恋",
    genre: "现实职场",
    recommendedSubtype: "职场恋爱",
    coreFantasy: "职业成长与亲密边界同步建立",
    audience: "偏好现实职场和成熟情感",
    openingFocus: "用职业目标与关系边界冲突开篇",
    taboo: "职场常识失真或权责悬空",
    conflictEngine: '让"职业晋升"和"关系边界"互相挤压——每次升职或换岗都要重新谈一次两人的位置。',
    payoffPattern: "第 1–3 章给一次职场破局，第 10–20 章给一次职位或关系转折，卷末兑现职业与关系定型。",
    expansionAxis: "个人岗位 → 团队与项目 → 公司与行业 → 职业与关系定型",
    fatigueSignal: "连续两轮职场只做背景，或关系冲突不涉及现实利益。",
    qualityChecks: [
      "本章的职场事件是否符合行业逻辑？",
      "关系冲突是否与职业选择直接相关？",
      "权责是否清晰？",
      "是否触发禁忌：职场常识失真？",
    ],
    narrativeGenres: ["恋爱", "经营"],
    genreElements: ["职场", "现代都市", "双强"],
    expansionRoutes: ["岗位破局", "团队与项目博弈", "行业与公司变动", "职业与关系定型"],
    tags: ["职场", "婚恋", "都市", "现实", "项目", "竞争", "情感", "成长"],
    siblingCategories: ["女频:745", "女频:749"],
    readerAgeBand: "24–40 岁，偏好现实职场与成熟情感",
    chapterHookStyle: "首章用一个职业目标与关系边界直接冲突的事件开局",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次职场或关系回报，每卷末一次职位级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["空降上司", "竞标撞车", "同组竞争"],
    clicheTraps: ["职场失真", "权责悬空", "关系冲突无现实代价"],
    differentiationAngles: ["行业逻辑写实", "关系与职业互相影响", "权责边界清晰"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:748",
    channel: "女频",
    categoryId: "748",
    name: "豪门总裁",
    genre: "现言甜宠",
    recommendedSubtype: "先婚后爱",
    coreFantasy: "身份资源与真实情感的反差确认",
    audience: "偏好强身份差和高反馈情绪",
    openingFocus: "先给契约/利益关系的明确条件",
    taboo: "霸总万能和重复误会",
    conflictEngine: '让"资源不对等"和"情感平等"互相冲突——每次接受资源都要重新确认关系的性质。',
    payoffPattern: "第 1–3 章给一次契约内的关系破冰，第 10–20 章给一次身份或契约转折，卷末兑现关系确认。",
    expansionAxis: "契约关系 → 家族与公司 → 身份与旧关系 → 关系定型",
    fatigueSignal: "连续两轮靠误会和资源碾压推进。",
    qualityChecks: [
      "本章的关系推进是否来自具体行动？",
      "资源不对等是否产生现实后果？",
      "主角是否有独立目标？",
      "是否触发禁忌：霸总万能和重复误会？",
    ],
    narrativeGenres: ["恋爱", "权谋"],
    genreElements: ["现代都市", "家族", "契约关系"],
    expansionRoutes: ["契约边界试探", "家族与公司介入", "身份与旧关系清算", "关系定型"],
    tags: ["豪门", "总裁", "先婚后爱", "契约", "身份差", "家族", "甜宠", "情感"],
    siblingCategories: ["女频:267", "男频:27"],
    readerAgeBand: "18–40 岁，偏好强身份差与情绪反馈",
    chapterHookStyle: "首章给出明确的契约/利益条件并立刻产生现实后果",
    firstPayoffWindow: [1, 3],
    payoffCadence: "每 2–4 章一次关系回报，每卷末一次关系阶段级回报",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["协议结婚", "替嫁", "家族安排"],
    clicheTraps: ["霸总万能", "误会循环", "女主无独立目标"],
    differentiationAngles: ["资源关系写清条款", "女主有独立事业线", "误会当场解决"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "女频:1017",
    channel: "女频",
    categoryId: "1017",
    name: "民国言情",
    genre: "历史/架空",
    recommendedSubtype: "庙堂权谋",
    coreFantasy: "时代动荡中的爱情、身份与家国选择",
    audience: "偏好历史氛围和情感牺牲",
    openingFocus: "让时代危机直接改变一段关系的选择",
    taboo: "时代只做服化道",
    conflictEngine: '让"个人情感"和"时代立场"互相逼迫——每次选择关系都要面对一次立场代价。',
    payoffPattern: "第 1–3 章给一次关系推进，第 10–20 章给一次立场或身份转折，卷末兑现家国与情感的双重选择。",
    expansionAxis: "个人关系 → 家族与商界 → 时局与阵营 → 家国与情感定型",
    fatigueSignal: "连续两轮只有氛围描写，或时代不影响关系选择。",
    qualityChecks: [
      "本章的时代局势是否改变了关系选择？",
      "人物立场是否具体？",
      "是否出现真实的时代限制？",
      "是否触发禁忌：时代只做服化道？",
    ],
    narrativeGenres: ["恋爱", "权谋"],
    genreElements: ["民国", "家族", "宫廷"],
    expansionRoutes: ["关系推进", "家族与商界博弈", "时局与阵营选择", "家国与情感定型"],
    tags: ["民国", "言情", "家国", "时代", "家族", "情感", "权谋", "牺牲"],
    siblingCategories: ["男频:504", "女频:1139"],
    readerAgeBand: "22–45 岁，偏好历史氛围与情感张力",
    chapterHookStyle: "首章让一次时代危机直接改变一段关系的选择",
    firstPayoffWindow: [3, 5],
    payoffCadence: "每 4–6 章一次关系或立场回报，每卷末一次家国级回报",
    typicalChapterWords: [2200, 3200],
    commonOpenings: ["留学归国", "家族联姻", "战乱离散"],
    clicheTraps: ["时代只做服化道", "立场脸谱化", "情感脱离时局"],
    differentiationAngles: ["时局改变关系", "立场各有代价", "情感选择有历史后果"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
];
