import type { FanqieCategoryProfile } from "./types";
import { FANQIE_PROFILE_VERSION } from "./types";

export const MALE_CATEGORY_PROFILES: FanqieCategoryProfile[] = [
  {
    key: "男频:1141",
    channel: "男频",
    categoryId: "1141",
    name: "西方奇幻",
    genre: "玄幻/仙侠",
    recommendedSubtype: "宗门升级",
    coreFantasy: "异域规则探索与力量成长",
    audience: "偏好世界探索和成长回报",
    openingFocus: "先展示异域规则，再让主角用一次有限能力破局",
    taboo: "只换名词的西式皮肤",
    conflictEngine:
      "把异域规则变成可验证的约束——主角每次用能力破局，都要先付出一次理解规则的代价（资源、时间或盟友信任）。",
    payoffPattern: '第 1–3 章给一次"看懂规则"的胜利，第 8–15 章给一次力量质变，卷末兑现领地或势力级回报。',
    expansionAxis: "单城邦规则 → 区域规则冲突 → 世界规则来源 → 规则制定权",
    fatigueSignal: "连续两轮只换地名和怪物名，或力量升级不再带来新选择。",
    qualityChecks: [
      "本章的异域规则是否产生了具体限制或代价？",
      "主角的胜利是否来自对规则的理解而非新道具？",
      "本章是否打开一处新的世界层级？",
      "是否触发禁忌：只换名词的西式皮肤？",
    ],
    narrativeGenres: ["成长", "冒险"],
    genreElements: ["异世界", "师徒", "双强"],
    expansionRoutes: ["规则边界试探", "势力与信仰重组", "世界规则来源揭露", "主角决定新秩序"],
    tags: ["西幻", "剑与魔法", "异世界", "位面", "神殿", "学院", "龙", "战争"],
    siblingCategories: ["男频:1140", "男频:258"],
    readerAgeBand: "16–30 岁，偏好世界观探索与设定感",
    chapterHookStyle: '用一次"规则反常"事件把主角推入无法回避的选择',
    firstPayoffWindow: [1, 3],
    payoffCadence: "每 5–8 章一次能力或认知回报，每卷末一次势力级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["穿越即得系统", "开局被驱逐后觉醒", "天赋测试打脸"],
    clicheTraps: ["换皮西幻", "无代价越阶", "设定堆砌不推进剧情"],
    differentiationAngles: ["用规则代价写文明冲突", "让配角遵守同一套规则", "把力量成长与制度选择绑定"],
    baselineDelta: {
      readerPromise: "异域规则探索 + 力量成长，且每次破局都要先付一次理解代价",
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:1140",
    channel: "男频",
    categoryId: "1140",
    name: "东方仙侠",
    genre: "玄幻/仙侠",
    recommendedSubtype: "凡人修仙",
    coreFantasy: "境界跃迁与道途选择",
    audience: "偏好修炼积累和境界质变",
    openingFocus: "用资源、代价和境界差制造首个不可回避的选择",
    taboo: "无代价越阶和境界数字膨胀",
    conflictEngine: '让"资源有限"和"道途排他"同时成立——每一步晋升都关闭另一条路，且要付出关系或寿命代价。',
    payoffPattern: "第 1–3 章给一次小境界突破，第 10–20 章给一次跨阶质变，卷末兑现宗门或道统地位。",
    expansionAxis: "资源争夺 → 道统分歧 → 上界规则 → 主角自成一脉",
    fatigueSignal: "突破只涨数字、敌人只按境界排队，或连续两轮换地图不换道途冲突。",
    qualityChecks: [
      "本章的晋升是否关闭了另一条路或付出了代价？",
      "敌人是否按利益而非境界数字行动？",
      "主角的道途选择是否比上一章更具体？",
      "是否触发禁忌：无代价越阶？",
    ],
    narrativeGenres: ["成长", "权谋"],
    genreElements: ["修仙界", "师徒", "家族"],
    expansionRoutes: ["资源与道途取舍", "宗门与道统博弈", "上界规则介入", "自开一脉接受检验"],
    tags: ["修仙", "凡人流", "宗门", "散修", "渡劫", "丹药", "剑修", "道侣"],
    siblingCategories: ["男频:1141", "男频:258"],
    readerAgeBand: "18–35 岁，偏好长期积累与体系感",
    chapterHookStyle: '用一个"必须现在选"的资源或道途取舍开局',
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 4–6 章一次境界或资源回报，每卷末一次道统级回报",
    typicalChapterWords: [2200, 3200],
    commonOpenings: ["废柴被逐", "捡到逆天功法", "灵根测试反转"],
    clicheTraps: ["越阶无代价", "境界数字膨胀", "宗门长辈集体降智"],
    differentiationAngles: ["把每次突破写成一次选择而非奖励", "用寿命/关系做硬成本", "让道途分歧贯穿全书"],
    baselineDelta: {
      rewardLadder: ["小境界", "跨阶质变", "道统地位", "自开一脉"],
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:8",
    channel: "男频",
    categoryId: "8",
    name: "科幻末世",
    genre: "科幻末世",
    recommendedSubtype: "异能规则",
    coreFantasy: "灾变生存与科技/能力升级",
    audience: "偏好危机压迫和规则揭秘",
    openingFocus: "把生存资源、未知威胁和能力边界同时落地",
    taboo: "灾难只做背景板",
    conflictEngine: '让"活下去"和"查清灾变原因"互相消耗——每次探索真相都要消耗当天的生存资源。',
    payoffPattern: "第 1–3 章给一次安全过夜，第 10–20 章给一次稳定据点，卷末兑现群体决策权。",
    expansionAxis: "单点求生 → 据点协作 → 灾变规则被掌握 → 灾变来源决定群体去向",
    fatigueSignal: "连续两轮只写搜物资清单，或威胁升级只换怪物外观。",
    qualityChecks: [
      "本章是否同时推进生存与真相两条线？",
      "资源消耗是否产生了新的取舍？",
      "威胁是否按规则行动而非按剧情需要？",
      "是否触发禁忌：灾难只做背景板？",
    ],
    narrativeGenres: ["生存", "冒险"],
    genreElements: ["末世", "系统", "群像"],
    expansionRoutes: ["资源缺口求生", "据点规则与人心", "灾变规则掌握", "来源揭露迫使长期选择"],
    tags: ["末世", "废土", "丧尸", "异能", "避难所", "囤货", "进化", "灾变"],
    siblingCategories: ["女频:8", "男频:262"],
    readerAgeBand: "18–35 岁，偏好压迫感与规则推演",
    chapterHookStyle: '灾变当天用一个"救谁/舍谁"的资源选择开局',
    firstPayoffWindow: [1, 3],
    payoffCadence: "每 3–5 章一次生存或能力回报，每卷末一次据点级回报",
    typicalChapterWords: [2200, 3200],
    commonOpenings: ["觉醒异能", "囤货空间", "重生回灾变当天"],
    clicheTraps: ["囤货清单替代人物行动", "威胁只做背景", "能力无边界"],
    differentiationAngles: ["把资源账算清", "让威胁也遵守规则", "用群体决策写人性"],
    baselineDelta: {
      readerPromise: "灾变环境下的生存压力、规则揭秘与资源重建",
      rewardLadder: ["活下来", "稳定据点", "掌握灾变规则", "决定群体去向"],
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:261",
    channel: "男频",
    categoryId: "261",
    name: "都市日常",
    genre: "都市脑洞",
    recommendedSubtype: "神豪经营",
    coreFantasy: "现实身份改善与可见生活反馈",
    audience: "偏好轻松节奏和现实回报",
    openingFocus: "用具体职业困境触发第一轮异常收益",
    taboo: "日常流水账和只报消费数字",
    conflictEngine: '让"收益"和"关系"互相拉扯——每次改善生活都会改变一段旧关系里的位置。',
    payoffPattern: "第 1–3 章给一次可验证的生活改善，第 10–20 章给一次身份跃迁，卷末兑现事业或家庭级回报。",
    expansionAxis: "个人收入 → 家庭与朋友圈 → 事业与人脉 → 社会身份与责任",
    fatigueSignal: "连续两轮只写消费和围观，或收益不改变任何关系。",
    qualityChecks: [
      "本章的收益是否改变了具体处境或关系？",
      "消费描写是否服务于人物选择？",
      "是否有新的现实约束出现？",
      "是否触发禁忌：日常流水账？",
    ],
    narrativeGenres: ["经营", "成长"],
    genreElements: ["现代都市", "职场", "家族"],
    expansionRoutes: ["单点收益验证", "人脉与家庭重组", "事业与制度博弈", "身份责任接受检验"],
    tags: ["都市", "神豪", "系统", "日常", "轻松", "装逼打脸", "家庭", "逆袭"],
    siblingCategories: ["男频:263", "男频:262"],
    readerAgeBand: "20–40 岁，偏好轻松与现实代入",
    chapterHookStyle: "用一个马上会造成损失的生活难题开局",
    firstPayoffWindow: [1, 2],
    payoffCadence: "每 2–4 章一次生活级回报，每卷末一次身份级回报",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["继承遗产", "系统到账", "中奖/捡漏"],
    clicheTraps: ["只报数字不写处境", "亲人集体势利", "消费流水账"],
    differentiationAngles: ["把每笔收益写成关系变化", "让现实规则（税务、合同、人情）真实存在", "用日常细节代替炫耀"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:124",
    channel: "男频",
    categoryId: "124",
    name: "都市修真",
    genre: "都市脑洞",
    recommendedSubtype: "异能规则",
    coreFantasy: "超凡规则嵌入现实秩序",
    audience: "偏好现代社会与修行反差",
    openingFocus: "先验证一条能力边界，再制造身份暴露压力",
    taboo: "修真体系覆盖现实逻辑",
    conflictEngine: '让"修行规则"和"现代社会规则"互相限制——每次动用能力都要处理监控、职业或法律后果。',
    payoffPattern: "第 1–3 章给一次能力验证，第 10–20 章给一次身份掩护升级，卷末兑现门派或组织级回报。",
    expansionAxis: "个人修行 → 隐世组织 → 现实秩序与修行界冲突 → 两套规则的重构",
    fatigueSignal: "连续两轮无视现实后果，或修真设定吞掉都市生活。",
    qualityChecks: [
      "本章的能力使用是否产生了现实后果？",
      "隐世规则是否与现代秩序发生具体摩擦？",
      "主角的暴露风险是否可追踪？",
      "是否触发禁忌：修真体系覆盖现实逻辑？",
    ],
    narrativeGenres: ["成长", "权谋"],
    genreElements: ["现代都市", "修仙界", "职场"],
    expansionRoutes: ["能力边界验证", "隐世组织关系", "两套规则冲突", "秩序重构"],
    tags: ["都市修真", "隐世", "灵气复苏", "门派", "异能", "身份隐藏", "现代", "修仙"],
    siblingCategories: ["男频:1014", "男频:262"],
    readerAgeBand: "18–35 岁，偏好现代与修行反差",
    chapterHookStyle: '用一次"能力在监控下暴露风险"的具体事件开局',
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 4–6 章一次能力或身份回报，每卷末一次组织级回报",
    typicalChapterWords: [2200, 3000],
    commonOpenings: ["灵气复苏觉醒", "得到传承", "隐藏身份进入都市"],
    clicheTraps: ["修真碾压现实逻辑", "身份暴露无人追究", "组织设定悬空"],
    differentiationAngles: ["把现实代价写实", "让隐世组织有自己的利益", "用两套规则冲突推动剧情"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:1014",
    channel: "男频",
    categoryId: "1014",
    name: "都市高武",
    genre: "都市脑洞",
    recommendedSubtype: "异能规则",
    coreFantasy: "现实秩序中的力量跃迁",
    audience: "偏好力量升级和城市危机",
    openingFocus: "把能力代价与现实制度绑定",
    taboo: "战力只靠口号升级",
    conflictEngine: '让"力量等级"和"社会责任"互相加压——战力越强，能回避的公共危机越少。',
    payoffPattern: "第 1–3 章给一次可量化的战力验证，第 10–20 章给一次城市级战功，卷末兑现制度内位置。",
    expansionAxis: "个人战力 → 小队与机构 → 城市危机 → 高武秩序与普通人权益",
    fatigueSignal: "连续两轮只换战力数字，或危机只由主角一人解决。",
    qualityChecks: [
      "本章的战力提升是否带来新的责任或约束？",
      "危机是否有普通人的视角？",
      "制度对主角的约束是否具体？",
      "是否触发禁忌：战力只靠口号升级？",
    ],
    narrativeGenres: ["成长", "群像"],
    genreElements: ["现代都市", "末世", "双强"],
    expansionRoutes: ["战力与制度绑定", "机构与小队成形", "城市级危机", "秩序与权益重构"],
    tags: ["高武", "现代", "异能", "学院", "武道", "危机", "组织", "升级"],
    siblingCategories: ["男频:124", "男频:262"],
    readerAgeBand: "16–32 岁，偏好热血与体系化战力",
    chapterHookStyle: '用一次"出手就要承担责任"的公共事件开局',
    firstPayoffWindow: [1, 3],
    payoffCadence: "每 3–5 章一次战力或战功回报，每卷末一次机构级回报",
    typicalChapterWords: [2200, 3200],
    commonOpenings: ["武考觉醒", "异兽入侵", "觉醒者学院"],
    clicheTraps: ["口号式升级", "危机只有主角在意", "配角工具化"],
    differentiationAngles: ["把制度约束写实", "给危机中的普通人视角", "让战力提升改变社会位置"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:273",
    channel: "男频",
    categoryId: "273",
    name: "历史古代",
    genre: "历史/架空",
    recommendedSubtype: "庙堂权谋",
    coreFantasy: "在真实制度约束下改变历史局面",
    audience: "偏好权谋、经营和时代选择",
    openingFocus: "先给出资源短缺和制度障碍",
    taboo: "现代价值直接碾压时代",
    conflictEngine: '让"想做的事"和"制度允许做的事"互相卡住——每一步改革都要先拿到合法性与资源。',
    payoffPattern: "第 1–3 章给一次局部破局，第 10–20 章给一次官职或势力跃迁，卷末兑现制度级改变。",
    expansionAxis: "一县一职 → 一州一军 → 朝堂格局 → 制度与时代走向",
    fatigueSignal: "连续两轮靠现代知识碾压，或敌人只靠道德败坏行动。",
    qualityChecks: [
      "本章的行动是否受时代制度约束？",
      "对手是否有合理的利益动机？",
      "改革是否付出了政治代价？",
      "是否触发禁忌：现代价值直接碾压时代？",
    ],
    narrativeGenres: ["权谋", "经营"],
    genreElements: ["古代", "架空王朝", "家族"],
    expansionRoutes: ["地方治理破局", "军事与财政成形", "朝堂联盟博弈", "制度改变接受检验"],
    tags: ["历史", "权谋", "种田", "朝堂", "军事", "经营", "改革", "争霸"],
    siblingCategories: ["男频:272", "男频:504"],
    readerAgeBand: "20–40 岁，偏好制度推演与历史感",
    chapterHookStyle: '用一个"资源见底 + 制度挡路"的具体困局开局',
    firstPayoffWindow: [3, 5],
    payoffCadence: "每 5–8 章一次治理或官职回报，每卷末一次格局级回报",
    typicalChapterWords: [2500, 3500],
    commonOpenings: ["穿越成小吏", "家族蒙冤", "边地任职"],
    clicheTraps: ["现代知识万能", "对手降智", "制度只做背景"],
    differentiationAngles: ["把制度成本写实", "给对手合理动机", "让每次改革都留下后患"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:27",
    channel: "男频",
    categoryId: "27",
    name: "战神赘婿",
    genre: "都市脑洞",
    recommendedSubtype: "系统成长",
    coreFantasy: "低位身份反转与实力/资源证明",
    audience: "偏好身份揭示和即时打脸反馈",
    openingFocus: "首章同时落下婚姻压力和可验证反转",
    taboo: "反复隐藏身份打脸",
    conflictEngine: '让"隐藏身份"和"保护家人"互相冲突——每次出手都可能暴露，而暴露会带来新的敌人。',
    payoffPattern: "第 1–2 章给一次打脸，第 10–20 章给一次身份半公开，卷末兑现家族或势力地位。",
    expansionAxis: "家庭内部 → 商圈与旧敌 → 隐藏身份的组织 → 身份公开后的责任",
    fatigueSignal: "连续两轮只写亲戚嘲讽和主角沉默，或打脸不改变家庭处境。",
    qualityChecks: [
      "本章的出手是否带来暴露风险？",
      "家人的处境是否真的改善？",
      "对手是否升级了手段？",
      "是否触发禁忌：反复隐藏身份打脸？",
    ],
    narrativeGenres: ["复仇", "成长"],
    genreElements: ["现代都市", "家族", "契约关系"],
    expansionRoutes: ["家庭处境改善", "旧敌网络显形", "组织身份揭晓", "公开身份后的责任"],
    tags: ["赘婿", "战神", "打脸", "隐藏身份", "都市", "家族", "逆袭", "爽文"],
    siblingCategories: ["男频:261", "男频:748"],
    readerAgeBand: "18–40 岁，偏好即时反馈与身份反差",
    chapterHookStyle: "首章 500 字内同时给出婚姻压力和一次可验证的出手",
    firstPayoffWindow: [1, 2],
    payoffCadence: "每 2–4 章一次打脸或身份回报，每卷末一次家族级回报",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["入赘被欺", "婚礼被辱", "隐藏身份回归"],
    clicheTraps: ["亲戚集体降智", "打脸循环", "身份永不公开"],
    differentiationAngles: ["让暴露成为剧情推进器", "给家人真实成长", "把对手写成有资源的组织"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:263",
    channel: "男频",
    categoryId: "263",
    name: "都市种田",
    genre: "都市脑洞",
    recommendedSubtype: "神豪经营",
    coreFantasy: "从小资源经营到现实影响力扩张",
    audience: "偏好经营反馈和稳定成长",
    openingFocus: "用一个可量化的经营难题开局",
    taboo: "只写采购和报表",
    conflictEngine: '让"扩张"和"口碑/现金流"互相制约——每开一处新业务都要先解决人、供应链或信任问题。',
    payoffPattern: "第 1–3 章给一次单点盈利，第 10–20 章给一次产业链成形，卷末兑现区域或行业地位。",
    expansionAxis: "单店/单项目 → 供应链与人 → 区域品牌 → 行业规则与责任",
    fatigueSignal: "连续两轮只写采购、装修和报表数字。",
    qualityChecks: [
      "本章的经营动作是否解决了具体的人或供应链问题？",
      "增长是否带来了新的管理成本？",
      "是否有人物关系随之变化？",
      "是否触发禁忌：只写采购和报表？",
    ],
    narrativeGenres: ["经营", "群像"],
    genreElements: ["现代都市", "经商", "乡村"],
    expansionRoutes: ["单点盈利验证", "供应链与团队", "区域品牌与竞争", "行业规则重构"],
    tags: ["种田", "经营", "都市", "创业", "供应链", "乡村", "轻喜", "成长"],
    siblingCategories: ["男频:261", "男频:272"],
    readerAgeBand: "20–40 岁，偏好稳定反馈与经营细节",
    chapterHookStyle: '用一个"这周不解决就亏钱"的具体经营难题开局',
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次经营回报，每卷末一次区域级回报",
    typicalChapterWords: [2000, 2800],
    commonOpenings: ["接手亏损小店", "返乡创业", "系统给第一桶金"],
    clicheTraps: ["流水账", "数字通胀", "竞争对手无脑使坏"],
    differentiationAngles: ["把管理成本写实", "让员工和客户有独立动机", "用供应链细节制造张力"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:258",
    channel: "男频",
    categoryId: "258",
    name: "传统玄幻",
    genre: "玄幻/仙侠",
    recommendedSubtype: "无敌横推",
    coreFantasy: "力量体系与世界层级不断打开",
    audience: "偏好热血升级和大世界探索",
    openingFocus: "先建立境界差与一次可见胜负",
    taboo: "战斗结果脱离规则",
    conflictEngine: '让"越级挑战"和"体系规则"互相校准——每次越级都要先找到体系漏洞并承担反噬。',
    payoffPattern: "第 1–3 章给一次越级胜利，第 10–20 章给一次世界层级突破，卷末兑现势力或大陆级回报。",
    expansionAxis: "一城 → 一域 → 一界 → 体系源头",
    fatigueSignal: "连续两轮战斗只靠爆发不讲规则，或新地图只是换名字。",
    qualityChecks: [
      "本章的胜负是否可由已建立的体系规则解释？",
      "越级是否付出了反噬或代价？",
      "新层级是否带来新的规则？",
      "是否触发禁忌：战斗结果脱离规则？",
    ],
    narrativeGenres: ["成长", "冒险"],
    genreElements: ["修仙界", "异世界", "双强"],
    expansionRoutes: ["体系漏洞利用", "势力与血脉之争", "世界层级打开", "体系源头揭露"],
    tags: ["玄幻", "无敌", "升级", "热血", "体系", "争霸", "大陆", "天骄"],
    siblingCategories: ["男频:1140", "男频:257"],
    readerAgeBand: "16–30 岁，偏好热血与力量体系",
    chapterHookStyle: "首章用一次境界差明显的冲突，让主角靠规则而非蛮力取胜",
    firstPayoffWindow: [1, 3],
    payoffCadence: "每 3–5 章一次战斗或层级回报，每卷末一次势力级回报",
    typicalChapterWords: [2200, 3200],
    commonOpenings: ["血脉觉醒", "家族被灭", "得到逆天传承"],
    clicheTraps: ["爆发式越级无解释", "新地图换皮", "反派排队送人头"],
    differentiationAngles: ["把体系规则写成硬约束", "让对手也用规则", "每次升级打开一个新问题"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:272",
    channel: "男频",
    categoryId: "272",
    name: "历史脑洞",
    genre: "历史/架空",
    recommendedSubtype: "技术种田",
    coreFantasy: "知识/技术改变时代资源配置",
    audience: "偏好历史代入和经营回报",
    openingFocus: "用一个技术清单解决迫在眉睫的现实问题",
    taboo: "万能现代知识包打天下",
    conflictEngine: '让"技术落地"和"时代条件"互相卡住——每项技术都要先解决材料、工匠和组织问题。',
    payoffPattern: "第 1–3 章给一次小技术见效，第 10–20 章给一次产业雏形，卷末兑现地区或朝堂级影响。",
    expansionAxis: "单件工具 → 作坊与工匠 → 产业与财政 → 时代制度",
    fatigueSignal: "连续两轮靠背知识解决一切，或技术落地跳过材料与人力。",
    qualityChecks: [
      "本章的技术是否受材料、工匠或组织条件限制？",
      "受益者与受损者是否具体？",
      "是否有人因技术改变立场？",
      "是否触发禁忌：万能现代知识包打天下？",
    ],
    narrativeGenres: ["经营", "权谋"],
    genreElements: ["古代", "架空王朝", "经商"],
    expansionRoutes: ["单点技术验证", "作坊与工匠组织", "产业与财政成形", "制度与时代改变"],
    tags: ["历史", "种田", "技术", "经营", "发明", "朝堂", "工匠", "崛起"],
    siblingCategories: ["男频:273", "男频:263"],
    readerAgeBand: "20–40 岁，偏好技术细节与历史推演",
    chapterHookStyle: '用一个"三日内必须解决"的生产或军需难题开局',
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 4–6 章一次技术或产业回报，每卷末一次地区级回报",
    typicalChapterWords: [2500, 3500],
    commonOpenings: ["穿越成工匠", "边地屯田", "军械危机"],
    clicheTraps: ["知识万能", "跳过材料与人力", "古人集体震惊"],
    differentiationAngles: ["把落地成本写实", "给守旧者合理利益", "让技术改变权力结构"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:539",
    channel: "男频",
    categoryId: "539",
    name: "悬疑脑洞",
    genre: "悬疑推理",
    recommendedSubtype: "异能规则",
    coreFantasy: "异常规则与案件真相互相验证",
    audience: "偏好解谜、惊险和信息增量",
    openingFocus: "首章给出可复核异常证据",
    taboo: "靠隐藏信息强行反转",
    conflictEngine: '让"查真相"和"规则代价"互相牵制——每查一步都要触发一次异常后果。',
    payoffPattern: "第 1–3 章给一次线索闭环，第 10–20 章给一次案件背后的规则揭露，卷末兑现主线真相的一层。",
    expansionAxis: "单案 → 案与案的规则关联 → 规则来源 → 规则背后的组织",
    fatigueSignal: "连续两轮靠新角色口述补信息，或反转无前置证据。",
    qualityChecks: [
      "本章的线索是否在之前出现过或可复核？",
      "异常规则是否产生了具体后果？",
      "读者的信息量是否真的增加了？",
      "是否触发禁忌：靠隐藏信息强行反转？",
    ],
    narrativeGenres: ["悬疑", "冒险"],
    genreElements: ["现代都市", "探案", "规则怪谈"],
    expansionRoutes: ["异常证据积累", "案件规则关联", "规则来源追索", "组织与真相摊牌"],
    tags: ["悬疑", "脑洞", "推理", "规则怪谈", "探案", "异常", "反转", "都市"],
    siblingCategories: ["男频:751", "女频:539"],
    readerAgeBand: "18–35 岁，偏好推理解谜与惊险",
    chapterHookStyle: "首章给出一个可复核的异常证据，并让主角做出第一次调查选择",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次线索闭环，每卷末一次主线真相推进",
    typicalChapterWords: [2200, 3000],
    commonOpenings: ["接手离奇案件", "目击异常", "被卷入规则"],
    clicheTraps: ["信息不对称式反转", "配角口述真相", "规则随时改"],
    differentiationAngles: ["所有反转前置证据", "规则一旦成立就不可改", "让调查本身付出代价"],
    baselineDelta: {
      readerPromise: "异常规则与案件真相互相验证，每次调查都触发一次规则后果",
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:262",
    channel: "男频",
    categoryId: "262",
    name: "都市脑洞",
    genre: "都市脑洞",
    recommendedSubtype: "系统成长",
    coreFantasy: "高概念规则快速改写现实困境",
    audience: "偏好快反馈、身份反差和连续奖励",
    openingFocus: "三章内完成能力试验和现实收益",
    taboo: "震惊循环和任务流水",
    conflictEngine: "让规则收益与现实代价同时发生——每次用规则解决问题，都必须在职业、关系或资源上留下新约束。",
    payoffPattern: "第 1–3 章给一次可见收益，第 8–12 章把收益升级为身份或资源变化，卷末兑现关系级回报。",
    expansionAxis: "单点规则 → 规则组合 → 规则被他人学会 → 规则来源与代价揭露",
    fatigueSignal: "连续两轮只换规则名词不换处境，或围观震惊代替实际结果。",
    qualityChecks: [
      "本章是否用规则解决了一个具体困境并留下代价？",
      "回报是否改变了处境而不只是旁人反应？",
      "主角对规则的认知是否更具体？",
      "是否触发禁忌：震惊循环和任务流水？",
    ],
    narrativeGenres: ["成长", "冒险"],
    genreElements: ["现代都市", "系统", "模拟器"],
    expansionRoutes: ["规则边界试探", "规则组合与代价叠加", "规则扩散后的秩序重建", "规则来源揭露"],
    tags: ["系统流", "签到流", "模拟器", "神豪", "回收站", "直播", "无限流", "脑洞"],
    siblingCategories: ["男频:261", "男频:124", "男频:539"],
    readerAgeBand: "18–35 岁，偏好快节奏与强钩子",
    chapterHookStyle: "首章 300 字内给出规则异常 + 主角第一次具体选择",
    firstPayoffWindow: [1, 3],
    payoffCadence: "每 3–5 章一次中回报，每卷末一次身份或资源级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["获得系统后立刻震惊全场", "签到/任务流连发奖励", "身份隐藏反复打脸"],
    clicheTraps: ["震惊循环", "任务流水账", "金手指无代价", "只涨数值不改变处境"],
    differentiationAngles: ["把规则代价写成现实职业成本", "用一次失败反推规则边界", "让回报改变关系而非数字"],
    baselineDelta: {
      readerPromise: "高概念规则改写现实困境，并让每次收益都改变一处具体处境",
      rewardLadder: ["即时收益", "处境改变", "身份变化", "规则主导权"],
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:257",
    channel: "男频",
    categoryId: "257",
    name: "玄幻脑洞",
    genre: "玄幻/仙侠",
    recommendedSubtype: "无敌横推",
    coreFantasy: "新规则带来的力量和世界反差",
    audience: "偏好高概念升级和意外解法",
    openingFocus: "先用规则漏洞完成一次有限胜利",
    taboo: "临时增加规则解释一切",
    conflictEngine: '让"钻规则空子"和"规则反噬"互相追逐——每次利用漏洞都会让规则本身发生一次变化。',
    payoffPattern: "第 1–3 章给一次漏洞胜利，第 10–20 章给一次规则改写，卷末兑现世界级影响。",
    expansionAxis: "单条规则 → 规则组合与冲突 → 规则被改写 → 规则意志",
    fatigueSignal: "连续两轮临时加设定圆场，或漏洞使用不再产生后果。",
    qualityChecks: [
      "本章用到的规则是否此前已建立？",
      "使用漏洞是否让规则发生变化或反噬？",
      "胜利是否来自推演而非新设定？",
      "是否触发禁忌：临时增加规则解释一切？",
    ],
    narrativeGenres: ["冒险", "成长"],
    genreElements: ["修仙界", "异世界", "系统"],
    expansionRoutes: ["规则漏洞推演", "规则组合冲突", "规则被改写", "规则意志与主角对抗"],
    tags: ["玄幻", "脑洞", "规则", "无敌", "设定流", "推演", "反差", "升级"],
    siblingCategories: ["男频:258", "男频:262"],
    readerAgeBand: "16–32 岁，偏好设定推演与意外解法",
    chapterHookStyle: "首章给出一个明确规则，并让主角用它完成一次出人意料的有限胜利",
    firstPayoffWindow: [1, 3],
    payoffCadence: "每 3–5 章一次规则或认知回报，每卷末一次世界级回报",
    typicalChapterWords: [2200, 3200],
    commonOpenings: ["规则降临", "获得规则视角", "进入规则世界"],
    clicheTraps: ["临时加设定", "规则前后矛盾", "主角靠作者开恩"],
    differentiationAngles: ["规则一旦写出就不可改", "每次钻空子都留下后遗症", "让对手也研究规则"],
    baselineDelta: {
      readerPromise: "新规则带来的力量与世界反差，胜利来自推演而非新设定",
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:751",
    channel: "男频",
    categoryId: "751",
    name: "悬疑灵异",
    genre: "悬疑推理",
    recommendedSubtype: "异能规则",
    coreFantasy: "诡异生存规则与真相追索",
    audience: "偏好恐惧、推理和禁忌探索",
    openingFocus: "先让规则造成具体损失，再给出可验证线索",
    taboo: "只靠氛围不推进真相",
    conflictEngine: '让"活下去"和"查清规则"互相冲突——每查一条规则，就要承担一次违反禁忌的风险。',
    payoffPattern: "第 1–3 章给一次规则保命，第 10–20 章给一次禁忌真相，卷末兑现主线背后的一层。",
    expansionAxis: "单一诡异 → 规则群 → 禁忌来源 → 禁忌背后的存在",
    fatigueSignal: "连续两轮只堆氛围不推进真相，或规则随意变化。",
    qualityChecks: [
      "本章的诡异规则是否明确且可遵守/可违反？",
      "是否付出了具体损失？",
      "线索是否推进了真相？",
      "是否触发禁忌：只靠氛围不推进真相？",
    ],
    narrativeGenres: ["悬疑", "生存"],
    genreElements: ["现代都市", "规则怪谈", "探案"],
    expansionRoutes: ["规则确认与保命", "规则群关联", "禁忌来源追索", "存在与真相摊牌"],
    tags: ["灵异", "悬疑", "规则怪谈", "恐怖", "民俗", "禁忌", "探案", "惊悚"],
    siblingCategories: ["男频:539", "女频:747"],
    readerAgeBand: "18–35 岁，偏好惊悚与规则解谜",
    chapterHookStyle: "首章用一次具体的诡异损失开局，并给出第一条可验证规则",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次规则或线索回报，每卷末一次主线真相推进",
    typicalChapterWords: [2200, 3000],
    commonOpenings: ["搬进凶宅", "接触禁忌仪式", "接手祖传铺子"],
    clicheTraps: ["氛围注水", "规则随意", "鬼怪无敌"],
    differentiationAngles: ["规则写得像合同一样可检验", "每次保命都要付代价", "真相层层可回溯"],
    baselineDelta: {
      readerPromise: "诡异规则下的生存与真相追索，每次探索都承担一次禁忌风险",
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:504",
    channel: "男频",
    categoryId: "504",
    name: "抗战谍战",
    genre: "军事谍战",
    recommendedSubtype: "庙堂权谋",
    coreFantasy: "时代危机中的情报、选择与组织成长",
    audience: "偏好历史真实感和行动压力",
    openingFocus: "用任务目标、身份风险和资源缺口开局",
    taboo: "用现代常识替代历史证据",
    conflictEngine: '让"完成任务"和"保住身份"互相消耗——每送出一份情报都要牺牲一条掩护线。',
    payoffPattern: "第 1–3 章给一次情报成功，第 10–20 章给一次组织位置提升，卷末兑现战局级影响。",
    expansionAxis: "单点情报 → 情报网 → 组织与敌我博弈 → 战局走向",
    fatigueSignal: "连续两轮靠巧合脱险，或敌人只靠愚蠢出错。",
    qualityChecks: [
      "本章的任务是否受时代条件与资源限制？",
      "对手是否有合理的情报能力？",
      "每次成功是否付出了掩护代价？",
      "是否触发禁忌：用现代常识替代历史证据？",
    ],
    narrativeGenres: ["权谋", "悬疑"],
    genreElements: ["民国", "探案", "群像"],
    expansionRoutes: ["单点情报任务", "情报网与内线", "组织与敌方博弈", "战局与时代走向"],
    tags: ["谍战", "抗战", "情报", "潜伏", "民国", "历史", "组织", "悬疑"],
    siblingCategories: ["男频:273", "女频:1017"],
    readerAgeBand: "25–45 岁，偏好历史质感与智斗",
    chapterHookStyle: '用一个"送不出去就死人"的情报任务开局',
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–6 章一次任务回报，每卷末一次组织级回报",
    typicalChapterWords: [2500, 3500],
    commonOpenings: ["潜伏进敌方机关", "被误认为叛徒", "接手断线联络"],
    clicheTraps: ["巧合脱险", "敌人降智", "现代知识穿越式碾压"],
    differentiationAngles: ["把情报成本写实", "让对手同样专业", "用时代细节而非口号营造压力"],
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:746",
    channel: "男频",
    categoryId: "746",
    name: "游戏体育",
    genre: "游戏竞技",
    recommendedSubtype: "系统成长",
    coreFantasy: "规则训练转化为赛场胜负与团队地位",
    audience: "偏好竞技反馈和技能成长",
    openingFocus: "首章明确比赛目标与可量化短板",
    taboo: "只写数值面板不写比赛",
    conflictEngine: '让"个人短板"和"团队战术"互相制约——每次补强个人能力都会改变队伍里的位置与信任。',
    payoffPattern: "第 1–3 章给一次训练见效，第 10–20 章给一次关键比赛胜利，卷末兑现职业或联赛位置。",
    expansionAxis: "个人技术 → 队伍配合 → 联赛与对手研究 → 职业体系与身份",
    fatigueSignal: "连续两轮只写面板数值，或比赛过程被跳过。",
    qualityChecks: [
      "本章是否有一场可复述的比赛/训练过程？",
      "短板补强是否改变了团队关系？",
      "对手是否针对主角做了准备？",
      "是否触发禁忌：只写数值面板不写比赛？",
    ],
    narrativeGenres: ["竞技", "成长"],
    genreElements: ["校园", "职场", "双强"],
    expansionRoutes: ["短板训练验证", "队伍配合成形", "联赛与对手升级", "职业身份与责任"],
    tags: ["竞技", "体育", "电竞", "联赛", "训练", "团队", "热血", "成长"],
    siblingCategories: ["女频:746", "男频:262"],
    readerAgeBand: "16–30 岁，偏好竞技与团队成长",
    chapterHookStyle: "首章给出一个可量化的短板和一场迫在眉睫的比赛",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次训练或比赛回报，每卷末一次联赛级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["被队伍淘汰", "替补上场", "青训营选拔"],
    clicheTraps: ["面板流水", "比赛略写", "对手只会嘴炮"],
    differentiationAngles: ["把比赛写完整", "让队友有独立目标", "对手研究主角并升级"],
    baselineDelta: {
      readerPromise: "训练与战术转化为赛场胜负和团队地位",
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:718",
    channel: "男频",
    categoryId: "718",
    name: "动漫衍生",
    genre: "快穿衍生",
    recommendedSubtype: "宗门升级",
    coreFantasy: "熟悉规则中的原创成长和关系重组",
    audience: "偏好世界观熟悉感与新鲜路线",
    openingFocus: "尽快给出原创角色目标和差异化代价",
    taboo: "复述原作和替代原主角",
    conflictEngine: '让"借用既有世界"和"原创角色独立目标"互相拉扯——每次利用熟悉设定都要承担偏离原作的代价。',
    payoffPattern: "第 1–3 章给一次原创角色立足，第 10–20 章给一次势力或关系重组，卷末兑现原创主线地位。",
    expansionAxis: "个人立足 → 原创势力 → 与原作格局的碰撞 → 新秩序",
    fatigueSignal: "连续两轮靠原作角色推动剧情，或原创角色沦为旁观者。",
    qualityChecks: [
      "本章的推进是否由原创角色完成？",
      "是否避免复述原作名场面？",
      "原创代价是否具体？",
      "是否触发禁忌：复述原作和替代原主角？",
    ],
    narrativeGenres: ["群像", "成长"],
    genreElements: ["异世界", "群像", "双强"],
    expansionRoutes: ["原创角色立足", "原创势力成形", "与原作格局碰撞", "新秩序建立"],
    tags: ["衍生", "同人", "动漫", "原创角色", "群像", "势力", "热血", "成长"],
    siblingCategories: ["男频:1016", "男频:258"],
    readerAgeBand: "16–28 岁，偏好熟悉世界观中的新故事",
    chapterHookStyle: "首章用原创角色的独立冲突建立阅读理由，而非依赖原作角色登场",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次立足或关系回报，每卷末一次势力级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["穿越进熟悉世界", "成为原作配角亲属", "获得原创身份"],
    clicheTraps: ["复述原作", "抢原作角色戏份", "设定硬套"],
    differentiationAngles: ["原创角色有独立目标", "不依赖名场面", "把熟悉规则用出新代价"],
    baselineDelta: {
      readerPromise: "熟悉世界中的原创成长与关系重组，不依赖原作角色推动",
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
  {
    key: "男频:1016",
    channel: "男频",
    categoryId: "1016",
    name: "男频衍生",
    genre: "快穿衍生",
    recommendedSubtype: "宗门升级",
    coreFantasy: "既有世界规则下的原创势力成长",
    audience: "偏好衍生代入和新主线",
    openingFocus: "用新角色的独立冲突建立阅读理由",
    taboo: "只做原作剧情搬运",
    conflictEngine: '让"借用既有势力"和"自建主线"互相制衡——每次借势都要先让原创势力付出一部分自主权。',
    payoffPattern: "第 1–3 章给一次原创立足，第 10–20 章给一次势力独立，卷末兑现新主线格局。",
    expansionAxis: "个人 → 原创势力 → 与原作势力博弈 → 新格局",
    fatigueSignal: "连续两轮只搬运原作剧情，或原创势力始终依附他人。",
    qualityChecks: [
      "本章主线是否由原创势力推动？",
      "借势是否付出了自主权代价？",
      "是否出现原作剧情搬运？",
      "是否触发禁忌：只做原作剧情搬运？",
    ],
    narrativeGenres: ["群像", "权谋"],
    genreElements: ["修仙界", "群像", "家族"],
    expansionRoutes: ["原创立足", "势力独立成形", "与原作势力博弈", "新格局确立"],
    tags: ["衍生", "同人", "原创势力", "群像", "权谋", "成长", "热血", "世界观"],
    siblingCategories: ["男频:718", "男频:258"],
    readerAgeBand: "16–28 岁，偏好世界观延展与新势力故事",
    chapterHookStyle: "首章用原创角色的独立利益冲突开局",
    firstPayoffWindow: [2, 4],
    payoffCadence: "每 3–5 章一次立足或势力回报，每卷末一次格局级回报",
    typicalChapterWords: [2000, 3000],
    commonOpenings: ["穿越成无名小卒", "加入原作边缘势力", "继承原创传承"],
    clicheTraps: ["剧情搬运", "原创角色工具化", "原作角色万能"],
    differentiationAngles: ["原创势力有独立利益", "借势要付代价", "新主线能独立成立"],
    baselineDelta: {
      readerPromise: "既有世界规则下的原创势力成长，不依赖原作剧情搬运",
    },
    profileVersion: FANQIE_PROFILE_VERSION,
  },
];
