import type { SubGenreSeed } from "./types";

export const FANQIE_SUBGENRE_SEEDS: SubGenreSeed[] = [
  // ===== 男频（32） =====
  // 玄幻 / 仙侠（8）
  {
    id: "m-eastern-fantasy",
    name: "东方玄幻",
    channel: "男频",
    parentCategoryKeys: ["男频:258"],
    coreFantasy: "在东方修行体系下靠境界与势力成长，每一次升级都要重新选择道统与阵营。",
    openingFocus: "先建立境界差与一次可见胜负，让主角靠体系规则而非蛮力赢得第一场。",
    commonOpenings: ["血脉觉醒后被家族重新审视", "家族被灭后带着传承踏上修行路", "宗门大比上一战成名"],
    clicheTraps: ["爆发式越级没有解释", "新地图只换名字不换规则", "反派排队送人头"],
    differentiationAngles: ["把体系规则写成硬约束", "让对手也研究并利用规则", "每次升级都打开一个新问题"],
    typicalTags: ["玄幻", "东方玄幻", "升级", "体系", "争霸", "热血", "道统"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-isekai-continent",
    name: "异世大陆",
    channel: "男频",
    parentCategoryKeys: ["男频:1141"],
    coreFantasy: "转生到规则迥异的异世界，靠理解并利用世界规则一步步立足与成长。",
    openingFocus: "先展示异域规则的反常之处，再让主角用一次有限能力破局。",
    commonOpenings: ["转生醒来成为异世界边境少年", "被召唤到异界后遭遇身份危机", "穿越成异族弃子从头学规则"],
    clicheTraps: ["只换名词的西式皮肤", "无代价越阶", "设定堆砌不推进剧情"],
    differentiationAngles: ["用规则代价写文明冲突", "让配角遵守同一套规则", "把力量成长与制度选择绑定"],
    typicalTags: ["异世界", "西幻", "剑与魔法", "转生", "位面", "规则", "成长"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [1, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-dynasty-hegemony",
    name: "王朝争霸",
    channel: "男频",
    parentCategoryKeys: ["男频:258"],
    coreFantasy: "从一城一地起家，靠势力扩张与政治联姻重塑天下格局。",
    openingFocus: "先给出主角手里唯一的势力底牌和一处迫在眉睫的吞并危机。",
    commonOpenings: ["继承濒临覆灭的边地小势力", "乱世开局手握一支残军", "联姻结盟换来第一块地盘"],
    clicheTraps: ["敌人只会送人头", "扩张不写粮草与人心", "靠一场战斗解决所有问题"],
    differentiationAngles: ["把粮草、财政与人心写成硬约束", "让盟友有自己的算盘", "每次扩张都留下治理难题"],
    typicalTags: ["争霸", "王朝", "权谋", "势力", "联姻", "热血", "长篇"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-high-martial-world",
    name: "高武世界",
    channel: "男频",
    parentCategoryKeys: ["男频:1014"],
    coreFantasy: "武道即社会秩序，主角在制度约束下完成力量跃迁与社会位置上升。",
    openingFocus: "把能力代价与现实制度绑定，首章就让主角面对一次出手后的责任。",
    commonOpenings: ["武考觉醒后进入学院", "异兽入侵当天被迫出手", "觉醒者学院开学考核"],
    clicheTraps: ["口号式升级", "危机只有主角在意", "配角工具化"],
    differentiationAngles: ["把制度约束写实", "给危机中的普通人视角", "让战力提升改变社会位置"],
    typicalTags: ["高武", "现代", "武道", "学院", "异能", "升级", "危机"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-primordial-apotheosis",
    name: "洪荒封神",
    channel: "男频",
    parentCategoryKeys: ["男频:1140"],
    coreFantasy: "在洪荒神话的先天格局中修行立身，每一次量劫都要押上道途与因果。",
    openingFocus: "先用一次先天格局的压迫把主角推入量劫，再给出他的第一份立身资源。",
    commonOpenings: ["穿越成洪荒小妖开启修行", "量劫将至被卷入先天因果", "拜入圣人门下成为记名弟子"],
    clicheTraps: ["圣人集体降智", "法宝堆砌没有代价", "量劫只做背景板"],
    differentiationAngles: ["把因果与功德写成硬成本", "让圣人也有利益算计", "每次选择都改变量劫走向"],
    typicalTags: ["洪荒", "封神", "神话", "修行", "量劫", "因果", "仙侠"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-mythic-cultivation",
    name: "神话修真",
    channel: "男频",
    parentCategoryKeys: ["男频:1140"],
    coreFantasy: "以神话谱系为背景修行，靠境界与功绩争夺神位与香火。",
    openingFocus: "先交代神话谱系的规则与主角的微末出身，再给一次神位相关的机会。",
    commonOpenings: ["觉醒上古神祇血脉", "误入神庙继承残缺神位", "香火断绝的小神重开神道"],
    clicheTraps: ["神位设定前后矛盾", "靠新法宝越阶", "神话人物集体降智"],
    differentiationAngles: ["把香火与神职写成可量化资源", "让神位争夺有制度成本", "神话谱系随主角行动变化"],
    typicalTags: ["神话", "修真", "神位", "香火", "上古", "仙侠", "成长"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-sword-cultivation",
    name: "剑修",
    channel: "男频",
    parentCategoryKeys: ["男频:1140"],
    coreFantasy: "以剑道专精为唯一主线，用纯粹换锋利，每一次破境都要付出代价。",
    openingFocus: "先立住剑道信念与一次可见的剑势差距，再让主角用一剑破局。",
    commonOpenings: ["剑冢中拔出一柄断剑", "被逐出师门后独自练剑", "以凡人之身挑战剑道天骄"],
    clicheTraps: ["剑意升级只涨数字", "对手只会用嘴看不起剑修", "剑道信念靠口号反复强调"],
    differentiationAngles: ["把剑道纯粹写成具体取舍", "让对手的剑理同样成立", "每次破境都改变主角对剑的理解"],
    typicalTags: ["剑修", "仙侠", "剑道", "专精", "纯粹", "破境", "成长"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-alchemy-cultivation",
    name: "丹修",
    channel: "男频",
    parentCategoryKeys: ["男频:1140"],
    coreFantasy: "以炼丹与医道为成长载体，靠资源、技艺与人脉一步步打开修行路。",
    openingFocus: "先给出一炉必须炼成的丹药和缺一味主药的困境。",
    commonOpenings: ["药童出身偷学丹方", "捡到残缺丹经从头验证", "家族丹药生意濒临破产"],
    clicheTraps: ["丹方万能无失败", "药材随手可得", "同行只会嫉妒使坏"],
    differentiationAngles: ["把丹方验证写成实验过程", "让药材受产地与季节限制", "丹道收益与人情债绑定"],
    typicalTags: ["丹修", "炼丹", "医道", "仙侠", "资源", "技艺", "成长"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  // 都市（6）
  {
    id: "m-urban-superpower",
    name: "都市异能",
    channel: "男频",
    parentCategoryKeys: ["男频:262"],
    coreFantasy: "现代都市中觉醒异能，在隐秘秩序里用能力改写自己的现实处境。",
    openingFocus: "三章内完成能力试验和第一次现实收益，并留下代价。",
    commonOpenings: ["意外觉醒异能后隐藏身份", "获得系统后第一次使用能力", "目击异能事件被卷入隐秘组织"],
    clicheTraps: ["震惊循环", "能力无边界", "任务流水账"],
    differentiationAngles: ["把规则代价写成职业成本", "用一次失败反推能力边界", "让收益改变关系而非数字"],
    typicalTags: ["都市", "异能", "系统", "隐秘组织", "脑洞", "成长", "现代"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-urban-life",
    name: "都市生活",
    channel: "男频",
    parentCategoryKeys: ["男频:261"],
    coreFantasy: "在都市日常里靠具体选择改善生活，让每一笔收益都改变一段关系。",
    openingFocus: "用一个马上会造成损失的生活难题开局，触发第一轮现实收益。",
    commonOpenings: ["继承一笔带债务的遗产", "失业当天收到意外收入", "接手家里快倒闭的小店"],
    clicheTraps: ["只报消费数字", "日常流水账", "亲人集体势利"],
    differentiationAngles: ["把每笔收益写成关系变化", "让现实规则真实存在", "用生活细节代替炫耀"],
    typicalTags: ["都市", "日常", "生活", "轻松", "家庭", "逆袭", "温情"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [1, 2],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-arcane-superpower",
    name: "异术超能",
    channel: "男频",
    parentCategoryKeys: ["男频:124"],
    coreFantasy: "超凡能力嵌入现代社会，主角每用一次力量都要处理监控、职业与法律后果。",
    openingFocus: "先验证一条能力边界，再制造一次身份暴露的压力。",
    commonOpenings: ["灵气复苏后觉醒异术", "得到传承后隐藏身份进入都市", "意外目击隐世组织行动"],
    clicheTraps: ["修真碾压现实逻辑", "身份暴露无人追究", "组织设定悬空"],
    differentiationAngles: ["把现实代价写实", "让隐世组织有自己的利益", "用两套规则冲突推动剧情"],
    typicalTags: ["都市修真", "异能", "隐世", "灵气复苏", "身份隐藏", "现代", "规则"],
    typicalChapterWords: [2200, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-entertainment-star",
    name: "娱乐明星",
    channel: "男频",
    parentCategoryKeys: ["男频:261"],
    coreFantasy: "在文娱行业里从底层起步，靠作品与口碑完成身份跃迁。",
    openingFocus: "先给出一个马上要开机的机会和主角可量化的短板。",
    commonOpenings: ["龙套演员意外救场", "被雪藏后接到小成本剧本", "选秀节目临时代替上场"],
    clicheTraps: ["只写热搜和红毯", "对手只会耍阴招", "行业规则失真"],
    differentiationAngles: ["把行业规则写实", "让作品成功有可追溯的过程", "竞争对手按行业逻辑出手"],
    typicalTags: ["娱乐圈", "明星", "事业", "成长", "都市", "竞争", "逆袭"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [1, 2],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-business-workplace",
    name: "商战职场",
    channel: "男频",
    parentCategoryKeys: ["男频:261"],
    coreFantasy: "以商业博弈与组织晋升为主线，靠判断与资源整合赢得位置。",
    openingFocus: "用一个可量化的商业难题或职场危机开局，给出权责与资源边界。",
    commonOpenings: ["空降接手亏损项目", "竞标当天方案被换", "被排挤后自立门户"],
    clicheTraps: ["对手无脑使坏", "数字通胀", "商战只靠饭局和人情"],
    differentiationAngles: ["把现金流与合同写实", "让对手有专业能力", "每次晋升带来新的权责"],
    typicalTags: ["商战", "职场", "都市", "经营", "竞争", "晋升", "现实"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-super-rich",
    name: "神豪",
    channel: "男频",
    parentCategoryKeys: ["男频:261"],
    coreFantasy: "资源骤然充足后，主角在消费、关系与身份重建中面对新的约束。",
    openingFocus: "先给出主角最缺钱的具体处境，再让第一笔资源到账并立刻产生后果。",
    commonOpenings: ["系统到账第一桶金", "继承巨额遗产附带条件", "中奖后第一次改变处境"],
    clicheTraps: ["只报数字不写处境", "消费流水账", "亲戚集体势利"],
    differentiationAngles: ["把每笔消费写成关系变化", "让税务、合同与人情真实存在", "用选择而非炫耀体现身份变化"],
    typicalTags: ["神豪", "系统", "都市", "消费", "逆袭", "打脸", "轻松"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [1, 2],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  // 科幻（6）
  {
    id: "m-interstellar-civilization",
    name: "星际文明",
    channel: "男频",
    parentCategoryKeys: ["男频:8"],
    coreFantasy: "从一艘船或一颗星球起步，在星际政治与文明冲突中扩张到文明层级。",
    openingFocus: "先落地主角所在文明的资源短板与一个外部威胁，再给第一次技术或外交破局。",
    commonOpenings: ["舰队覆灭后接手残部", "边境星球遭遇文明级威胁", "星际学院毕业即被卷入战争"],
    clicheTraps: ["文明设定只换名字", "科技升级无成本", "外星敌人只靠蛮力"],
    differentiationAngles: ["把资源与后勤写成硬约束", "让不同文明有自己的逻辑", "每次扩张带来治理难题"],
    typicalTags: ["星际", "文明", "科幻", "战争", "扩张", "政治", "成长"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [2, 5],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-time-travel",
    name: "时空穿梭",
    channel: "男频",
    parentCategoryKeys: ["男频:8"],
    coreFantasy: "以时间线为变量反复穿梭，每一次改动都会留下不可逆的后果。",
    openingFocus: "先用一次失败的穿梭展示规则与代价，再给出主角必须回到的节点。",
    commonOpenings: ["意外获得穿梭装置", "醒来回到灾变前一天", "为救人第一次穿梭却改错节点"],
    clicheTraps: ["时间线随意重置", "穿梭无代价", "靠信息差碾压一切"],
    differentiationAngles: ["把每次穿梭的代价写清", "让改动产生连锁反应", "用规则限制而非作者开恩"],
    typicalTags: ["时空穿梭", "时间线", "科幻", "末世", "规则", "代价", "脑洞"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-future-world",
    name: "未来世界",
    channel: "男频",
    parentCategoryKeys: ["男频:8"],
    coreFantasy: "在近未来科技秩序下求生与上升，身份与数据成为新的资源。",
    openingFocus: "先展示未来秩序的规则与主角的身份短板，再给一次可验证的破局。",
    commonOpenings: ["底层居民身份被系统误判", "获得一份来路不明的权限", "在巨型城市里接手高风险任务"],
    clicheTraps: ["未来设定只堆名词", "科技解决一切", "社会秩序只做背景"],
    differentiationAngles: ["把身份与权限写成可交易资源", "让制度约束具体可感", "用底层视角写科技秩序"],
    typicalTags: ["未来世界", "科幻", "赛博", "生存", "身份", "科技", "秩序"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-apocalypse-crisis",
    name: "末世危机",
    channel: "男频",
    parentCategoryKeys: ["男频:8"],
    coreFantasy: "灾变之后靠资源账与群体协作活下去，并逐步掌握灾变规则。",
    openingFocus: "灾变当天用一个救谁舍谁的资源选择开局，同时落地威胁规则。",
    commonOpenings: ["重生回灾变当天", "觉醒异能后第一次搜物资", "避难所名额只剩一个"],
    clicheTraps: ["囤货清单替代人物行动", "威胁只做背景", "能力无边界"],
    differentiationAngles: ["把资源账算清", "让威胁也遵守规则", "用群体决策写人性"],
    typicalTags: ["末世", "废土", "生存", "丧尸", "囤货", "据点", "灾变"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-super-tech",
    name: "超级科技",
    channel: "男频",
    parentCategoryKeys: ["男频:8"],
    coreFantasy: "以技术突破为成长载体，每项发明都要先解决材料、工艺与组织问题。",
    openingFocus: "用一个必须尽快解决的技术难题开局，让主角从材料清单开始。",
    commonOpenings: ["实验室事故后获得关键技术", "接手被放弃的研发项目", "在灾变中重建基础工业"],
    clicheTraps: ["技术跳过落地过程", "知识万能", "同行只会拖后腿"],
    differentiationAngles: ["把材料与工艺成本写实", "让技术改变利益格局", "每次突破打开新的工程难题"],
    typicalTags: ["科技", "发明", "科幻", "工业", "经营", "突破", "硬核"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-cyberpunk",
    name: "赛博朋克",
    channel: "男频",
    parentCategoryKeys: ["男频:8"],
    coreFantasy: "在高技术与低生活的都市里，用改造与信息换取生存与身份。",
    openingFocus: "先给出主角的身体或身份负债，再让一次委托把他拖进更大的局。",
    commonOpenings: ["欠下义体贷款被迫接活", "接下一次来路不明的数据窃取", "身份档案被人篡改后追查真相"],
    clicheTraps: ["霓虹滤镜代替社会结构", "黑客万能", "公司只做反派脸谱"],
    differentiationAngles: ["把义体与数据写成债务", "让公司有自己的利益逻辑", "用底层视角写技术代价"],
    typicalTags: ["赛博朋克", "科幻", "义体", "黑客", "公司", "反乌托邦", "身份"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  // 历史（4）
  {
    id: "m-transmigration-hegemony",
    name: "穿越争霸",
    channel: "男频",
    parentCategoryKeys: ["男频:273"],
    coreFantasy: "穿越到乱世，在制度约束下扩张势力，逐步改写天下格局。",
    openingFocus: "先给出资源短缺和制度障碍，再让主角完成一次局部破局。",
    commonOpenings: ["穿越成边地小吏", "乱世中接手一支残军", "穿越成被排挤的宗室子弟"],
    clicheTraps: ["现代知识万能", "对手降智", "制度只做背景"],
    differentiationAngles: ["把制度成本写实", "给对手合理动机", "每次改革都留下后患"],
    typicalTags: ["穿越", "争霸", "历史", "权谋", "军事", "种田", "格局"],
    typicalChapterWords: [2500, 3500],
    firstPayoffWindow: [3, 5],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-court-intrigue",
    name: "权谋朝堂",
    channel: "男频",
    parentCategoryKeys: ["男频:273"],
    coreFantasy: "在朝堂博弈与制度约束下推动改革，每一步都要先拿到合法性与资源。",
    openingFocus: "用一个资源见底加制度挡路的具体困局开局。",
    commonOpenings: ["科举入仕后被卷入党争", "家族蒙冤后进京翻案", "接手一桩无人敢办的差事"],
    clicheTraps: ["现代价值直接碾压时代", "敌人只靠道德败坏行动", "权谋靠口才而非利益"],
    differentiationAngles: ["把政治代价写实", "让对手有合理利益", "改革留下可追踪的后患"],
    typicalTags: ["权谋", "朝堂", "历史", "改革", "博弈", "古代", "智斗"],
    typicalChapterWords: [2500, 3500],
    firstPayoffWindow: [3, 5],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-border-military",
    name: "边关军旅",
    channel: "男频",
    parentCategoryKeys: ["男频:273"],
    coreFantasy: "从边关军旅视角写战争与治理，靠军功与制度空间改变局面。",
    openingFocus: "先给出一次迫在眉睫的边防危机和主角有限的兵员粮草。",
    commonOpenings: ["被贬到边关担任低阶军官", "边镇遭遇突袭临危受命", "接手一支欠饷的边军"],
    clicheTraps: ["战争只写冲锋", "粮草军饷从不短缺", "敌军只会莽撞送死"],
    differentiationAngles: ["把后勤与军纪写实", "让敌军有战术", "军功与朝堂博弈挂钩"],
    typicalTags: ["边关", "军旅", "历史", "战争", "治理", "古代", "热血"],
    typicalChapterWords: [2500, 3500],
    firstPayoffWindow: [3, 5],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-tech-nation-building",
    name: "技术兴国",
    channel: "男频",
    parentCategoryKeys: ["男频:272"],
    coreFantasy: "把现代技术落地到古代产业，靠一项项工程推动国力与制度变化。",
    openingFocus: "用一个三日内必须解决的生产或军需难题开局。",
    commonOpenings: ["穿越成工匠接手军械危机", "边地屯田遇上农具短缺", "接手一座濒临停工的作坊"],
    clicheTraps: ["知识万能", "跳过材料与人力", "古人集体震惊"],
    differentiationAngles: ["把落地成本写实", "给守旧者合理利益", "让技术改变权力结构"],
    typicalTags: ["技术", "兴国", "历史", "种田", "产业", "经营", "工匠"],
    typicalChapterWords: [2500, 3500],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  // 游戏 / 体育（3）
  {
    id: "m-esports",
    name: "电子竞技",
    channel: "男频",
    parentCategoryKeys: ["男频:746"],
    coreFantasy: "在赛训体系里补强短板，用一场场胜负换来队伍位置与职业身份。",
    openingFocus: "首章明确比赛目标与一个可量化短板。",
    commonOpenings: ["被主力队淘汰后加入青训", "临时替补上场救火", "青训营选拔赛一战成名"],
    clicheTraps: ["面板流水", "比赛略写", "对手只会嘴炮"],
    differentiationAngles: ["把比赛过程写完整", "让队友有独立目标", "对手研究主角并升级"],
    typicalTags: ["电竞", "竞技", "游戏", "联赛", "团队", "训练", "热血"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-vrmmo",
    name: "虚拟网游",
    channel: "男频",
    parentCategoryKeys: ["男频:746"],
    coreFantasy: "在虚拟网游里探索规则并经营公会，用信息差与团队位置换取成长。",
    openingFocus: "首章交代游戏规则与主角可用的唯一优势，再给一次可验证的收益。",
    commonOpenings: ["全息网游开服抢注隐藏职业", "接手濒临解散的公会", "意外触发唯一任务链"],
    clicheTraps: ["数值面板代替剧情", "隐藏职业无敌", "公会成员只会拖累"],
    differentiationAngles: ["把游戏规则写成硬约束", "让公会管理有真实成本", "对手也用信息差竞争"],
    typicalTags: ["虚拟网游", "游戏", "公会", "全息", "规则", "经营", "升级"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-sports-competition",
    name: "体育竞技",
    channel: "男频",
    parentCategoryKeys: ["男频:746"],
    coreFantasy: "在项目训练与赛事体系下成长，用可复述的比赛过程换来职业位置。",
    openingFocus: "首章给出一个可量化的技术短板和一场迫在眉睫的比赛。",
    commonOpenings: ["被队伍淘汰后独自加练", "替补上场完成关键一战", "体校选拔中被教练看中"],
    clicheTraps: ["训练过程被跳过", "对手只会挑衅", "天赋解决一切"],
    differentiationAngles: ["把训练与战术写细", "让队友有独立目标", "对手针对主角做针对性部署"],
    typicalTags: ["体育", "竞技", "赛事", "训练", "团队", "热血", "成长"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  // 悬疑（5）
  {
    id: "m-detective-mystery",
    name: "侦探推理",
    channel: "男频",
    parentCategoryKeys: ["男频:539"],
    coreFantasy: "以证据链与逻辑推演驱动案件主线，每条线索都必须可复核。",
    openingFocus: "首章给出可复核的异常证据，并让主角做出第一次调查选择。",
    commonOpenings: ["接手一桩离奇命案", "目击异常后主动调查", "被卷入案件成为嫌疑人"],
    clicheTraps: ["信息不对称式反转", "配角口述真相", "证据凭空出现"],
    differentiationAngles: ["所有反转前置证据", "让调查付出代价", "对手也在推演主角"],
    typicalTags: ["侦探", "推理", "悬疑", "证据链", "探案", "反转", "都市"],
    typicalChapterWords: [2200, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-occult-mystery",
    name: "诡秘悬疑",
    channel: "男频",
    parentCategoryKeys: ["男频:751"],
    coreFantasy: "在规则怪谈与禁忌探索中求生，每查一条规则都要承担一次风险。",
    openingFocus: "先让规则造成具体损失，再给出第一条可验证的线索。",
    commonOpenings: ["搬进一栋规则异常的凶宅", "接触禁忌仪式后被盯上", "接手祖传铺子遇上怪事"],
    clicheTraps: ["氛围注水不推进真相", "规则随意变化", "鬼怪无敌无解"],
    differentiationAngles: ["规则写得像合同一样可检验", "每次保命都要付代价", "真相层层可回溯"],
    typicalTags: ["诡秘", "悬疑", "规则怪谈", "灵异", "禁忌", "恐怖", "探案"],
    typicalChapterWords: [2200, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-expedition-survival",
    name: "探险生存",
    channel: "男频",
    parentCategoryKeys: ["男频:751"],
    coreFantasy: "在未知环境里探索求生，靠资源分配与同伴信任逼近真相。",
    openingFocus: "先给出探索目标与一次资源危机，让队伍内部先出现分歧。",
    commonOpenings: ["跟随考察队进入无人区", "船只失事后流落孤岛", "接手一次高报酬的探险委托"],
    clicheTraps: ["同伴只会拖后腿", "资源凭空出现", "危险只靠突然袭击"],
    differentiationAngles: ["把资源与体力写成硬约束", "让同伴各有动机", "危险有可推演的规律"],
    typicalTags: ["探险", "生存", "悬疑", "未知", "资源", "同伴", "惊悚"],
    typicalChapterWords: [2200, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-rule-horror",
    name: "规则怪谈",
    channel: "男频",
    parentCategoryKeys: ["男频:751"],
    coreFantasy: "以可检验的诡异规则为核心谜题，违规即付代价，破局靠推演。",
    openingFocus: "首章给出第一条明确规则和一次具体的违规损失。",
    commonOpenings: ["醒来发现自己身处规则空间", "入职手册第一页写着禁忌", "进入一栋规则明确的老楼"],
    clicheTraps: ["临时增加规则解释一切", "规则前后矛盾", "主角靠作者开恩"],
    differentiationAngles: ["规则一旦写出就不可改", "每次钻空子都留下后遗症", "让对手也研究规则"],
    typicalTags: ["规则怪谈", "悬疑", "灵异", "禁忌", "推演", "恐怖", "脑洞"],
    typicalChapterWords: [2200, 3000],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "m-folklore-horror",
    name: "民俗怪谈",
    channel: "男频",
    parentCategoryKeys: ["男频:751"],
    coreFantasy: "在地方民俗与禁忌体系下追索灵异真相，规矩背后各有来历。",
    openingFocus: "先用一次民俗禁忌造成的具体损失开局，再给出可查证的线索。",
    commonOpenings: ["回乡奔丧遇上祖宅怪事", "接手村里的祭祀差事", "调查一桩民俗相关的失踪案"],
    clicheTraps: ["民俗只做猎奇点缀", "禁忌无来源", "长辈只负责吓人"],
    differentiationAngles: ["把民俗规矩写出传承逻辑", "让禁忌有可追溯的来历", "真相落到具体的人而非鬼"],
    typicalTags: ["民俗", "怪谈", "灵异", "禁忌", "悬疑", "乡土", "恐怖"],
    typicalChapterWords: [2200, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },

  // ===== 女频（28） =====
  // 古代言情（8）
  {
    id: "f-palace-intrigue",
    name: "宫斗",
    channel: "女频",
    parentCategoryKeys: ["女频:246"],
    coreFantasy: "在后宫位分与权力结构中求生，每次上位都要付出关系或名声代价。",
    openingFocus: "首章给出一个可验证的宫闱危机与有限资源。",
    commonOpenings: ["入宫选秀被卷入位分之争", "被诬陷后自证清白", "替嫁入宫成为低位妃嫔"],
    clicheTraps: ["反派降智", "证据凭空出现", "主角无代价"],
    differentiationAngles: ["证据链可回溯", "对手手段专业", "每次赢都有关系损失"],
    typicalTags: ["宫斗", "古言", "权谋", "位分", "宫廷", "女性成长", "反转"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-household-intrigue",
    name: "宅斗",
    channel: "女频",
    parentCategoryKeys: ["女频:246"],
    coreFantasy: "在内宅资源与名声博弈中立足，每次赢下一局都要在信任上付账。",
    openingFocus: "给出一个可验证的家宅危机与有限资源。",
    commonOpenings: ["嫁入高门第一天就遭刁难", "重生回被算计的关键节点", "被诬陷后开始查证据"],
    clicheTraps: ["反派降智", "算计堆砌无情感", "长辈脸谱化"],
    differentiationAngles: ["证据链可回溯", "让配角有独立立场", "每次赢都改变关系格局"],
    typicalTags: ["宅斗", "古言", "内宅", "权谋", "证据", "家族", "女性成长"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-court-scheming",
    name: "权谋",
    channel: "女频",
    parentCategoryKeys: ["女频:1139"],
    coreFantasy: "以朝局与家国为背景展开智斗，每次选择都要牺牲情感或体面。",
    openingFocus: "首章同时给出婚约或家族压力与主角不肯退让的底线。",
    commonOpenings: ["家族落难后独自支撑门庭", "替嫁进权贵之家", "被卷入朝堂党争"],
    clicheTraps: ["只有权谋没有情感代价", "反派降智", "时代背景当摆设"],
    differentiationAngles: ["每次选择都有情感成本", "家国线与情感线互相推动", "让配角有独立立场"],
    typicalTags: ["权谋", "古言", "家国", "朝局", "智斗", "情感", "女性成长"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-physician-consort",
    name: "医妃",
    channel: "女频",
    parentCategoryKeys: ["女频:1139"],
    coreFantasy: "以医术为立身之本，在后宅与宫廷之间用专业能力换取话语权。",
    openingFocus: "先让主角用一次医术救人立信，再落下身份与婚姻压力。",
    commonOpenings: ["穿越成被退婚的庶女凭医术翻身", "入宫为医女卷入宫廷", "家族落难后靠医术支撑门庭"],
    clicheTraps: ["医术万能无失败", "药材随手可得", "只写打脸不写医理"],
    differentiationAngles: ["把诊疗过程写得可信", "让医术带来人情债与风险", "医术与权谋互相牵制"],
    typicalTags: ["医妃", "医术", "古言", "宫廷", "后宅", "权谋", "女性成长"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-pastoral-life",
    name: "田园",
    channel: "女频",
    parentCategoryKeys: ["女频:23"],
    coreFantasy: "在古代乡村经营家庭与生计，每改善一处条件都会改变家中关系。",
    openingFocus: "用一个这周不解决就断粮的生活难题开局。",
    commonOpenings: ["嫁进穷家后从头持家", "重生回灾年提前囤粮", "接手破败的田庄"],
    clicheTraps: ["只罗列生产流程", "亲戚脸谱化", "时代政策失真"],
    differentiationAngles: ["每次改善都改关系", "把政策与资源约束写实", "让配角有真实动机"],
    typicalTags: ["田园", "种田", "古言", "乡村", "家庭", "经营", "温情"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-rebirth-revenge",
    name: "重生复仇",
    channel: "女频",
    parentCategoryKeys: ["女频:253"],
    coreFantasy: "重生后逐层清算旧债，每推进一次复仇都要重新回答自己要成为谁。",
    openingFocus: "首章明确旧债、第一份证据和反击目标。",
    commonOpenings: ["重生回被害之前", "被陷害后归来复仇", "替身身份被拆穿后反杀"],
    clicheTraps: ["复仇清单化", "反派排队送", "主角手段无代价"],
    differentiationAngles: ["每步复仇都改变主角", "对手会反制", "终点是自我选择而非单纯清算"],
    typicalTags: ["重生", "复仇", "古言", "逆袭", "智斗", "女性成长", "反转"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-substitute-bride",
    name: "替嫁",
    channel: "女频",
    parentCategoryKeys: ["女频:1139"],
    coreFantasy: "以身份替换开局，在名声与真实关系之间反复取舍与自证。",
    openingFocus: "首章同时给出替嫁的压力和主角不可退让的底线。",
    commonOpenings: ["姐姐逃婚后被推上花轿", "替嫁进传闻中克妻的府邸", "重生后仍被安排替嫁"],
    clicheTraps: ["身份真相迟迟不揭", "夫家全员刁难", "靠误会推进感情"],
    differentiationAngles: ["让替嫁带来具体利益与风险", "对手也有难处", "身份揭露改变关系而非终结"],
    typicalTags: ["替嫁", "古言", "身份替换", "婚约", "情感", "权谋", "女性成长"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-strong-heroine",
    name: "女强",
    channel: "女频",
    parentCategoryKeys: ["女频:253"],
    coreFantasy: "以女性主体性成长为主线，在规则漏洞中争取选择权与位置。",
    openingFocus: "首章给出主角明确的目标与一处必须打破的规则。",
    commonOpenings: ["被退婚后自立门户", "家族落难后接手产业", "女扮男装进入仕途"],
    clicheTraps: ["强大只靠口号", "男主随时救场", "对手只会轻视女性"],
    differentiationAngles: ["把每次突破写成具体博弈", "让男主有独立立场而非救世主", "对手按利益而非偏见行动"],
    typicalTags: ["女强", "古言", "主体性", "成长", "智斗", "逆袭", "权谋"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  // 现代言情（8）
  {
    id: "f-tycoon-romance",
    name: "豪门总裁",
    channel: "女频",
    parentCategoryKeys: ["女频:748"],
    coreFantasy: "在身份资源差中确认真实情感，每次接受资源都要重新定义关系。",
    openingFocus: "首章给出明确的契约或利益条件并立刻产生现实后果。",
    commonOpenings: ["协议结婚各取所需", "替嫁进豪门", "家族安排联姻"],
    clicheTraps: ["霸总万能", "误会循环", "女主无独立目标"],
    differentiationAngles: ["资源关系写清条款", "女主有独立事业线", "误会当场解决"],
    typicalTags: ["豪门", "总裁", "先婚后爱", "契约", "身份差", "甜宠", "情感"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-marriage-first",
    name: "先婚后爱",
    channel: "女频",
    parentCategoryKeys: ["女频:267"],
    coreFantasy: "从契约关系开始，在现实条件下一点点重建亲密边界与信任。",
    openingFocus: "首章让契约关系立刻产生一个现实后果。",
    commonOpenings: ["协议结婚后同住", "替嫁后先立规矩", "同居契约到期前的相处"],
    clicheTraps: ["误会循环", "撒糖无剧情", "男主全能"],
    differentiationAngles: ["契约条款写清楚", "每次靠近都有代价", "配角有独立利益"],
    typicalTags: ["先婚后爱", "契约", "现言", "甜宠", "都市", "情感", "边界"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-second-chance",
    name: "破镜重圆",
    channel: "女频",
    parentCategoryKeys: ["女频:1015"],
    coreFantasy: "旧关系重启后处理信任与改变，用新的选择重新定义彼此的位置。",
    openingFocus: "首章给出女主独立欲望与一处旧关系缺口。",
    commonOpenings: ["多年后重逢旧爱", "离婚后因工作再度共事", "回到旧地重遇故人"],
    clicheTraps: ["靠回忆撑情感", "误会反复", "女主只做旁观者"],
    differentiationAngles: ["关系由行动改变", "双方都有独立目标", "旧问题必须被具体解决"],
    typicalTags: ["破镜重圆", "重逢", "现言", "情感", "信任", "成长", "都市"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-workplace-romance",
    name: "职场婚恋",
    channel: "女频",
    parentCategoryKeys: ["女频:750"],
    coreFantasy: "在职场晋升与亲密关系之间同步建立边界，每次升职都要重谈位置。",
    openingFocus: "首章用一个职业目标与关系边界直接冲突的事件开局。",
    commonOpenings: ["空降上司成了旧识", "竞标撞车与对手合作", "同组竞争中被卷入关系"],
    clicheTraps: ["职场失真", "权责悬空", "关系冲突无现实代价"],
    differentiationAngles: ["行业逻辑写实", "关系与职业互相影响", "权责边界清晰"],
    typicalTags: ["职场", "婚恋", "都市", "现实", "边界", "成长", "情感"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-youth-sweet",
    name: "青春甜宠",
    channel: "女频",
    parentCategoryKeys: ["女频:749"],
    coreFantasy: "在成长阶段互相陪伴，用具体行动确认关系与各自的选择。",
    openingFocus: "首章用具体成长目标制造一次关系靠近与阻碍。",
    commonOpenings: ["同桌或室友初遇结缘", "面试撞车后相识", "重逢旧识重新靠近"],
    clicheTraps: ["暧昧循环", "成长线停滞", "配角工具化"],
    differentiationAngles: ["关系与目标互相牵制", "每次靠近都要付行动成本", "配角有独立成长"],
    typicalTags: ["青春", "甜宠", "校园", "恋爱", "成长", "陪伴", "轻松"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-entertainment-circle",
    name: "娱乐圈",
    channel: "女频",
    parentCategoryKeys: ["女频:745"],
    coreFantasy: "在曝光与竞争中上升，每次事业进展都会让私人关系承受审视。",
    openingFocus: "首章同时给出一个事业机会和一次公开风险。",
    commonOpenings: ["替演救场意外走红", "被雪藏后凭作品翻红", "签约风波中被推上风口"],
    clicheTraps: ["只写炫耀", "舆论当背景", "对手无专业度"],
    differentiationAngles: ["行业规则写实", "曝光必然影响关系", "对手按行业逻辑出手"],
    typicalTags: ["娱乐圈", "星光", "事业", "恋爱", "舆论", "竞争", "成长"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-marriage-family",
    name: "婚恋家庭",
    channel: "女频",
    parentCategoryKeys: ["女频:750"],
    coreFantasy: "在家庭结构与婚恋关系里处理现实议题，每次让步都改变家庭格局。",
    openingFocus: "用一个具体的家庭矛盾与资源约束开局，明确各方立场。",
    commonOpenings: ["婚后与婆家同住矛盾爆发", "家庭变故后重新分工", "复婚或再婚前的现实谈判"],
    clicheTraps: ["亲戚脸谱化", "矛盾只靠吵架", "现实成本被忽略"],
    differentiationAngles: ["把家庭资源与责任写实", "让每个立场都有理由", "矛盾靠协商与行动解决"],
    typicalTags: ["婚恋", "家庭", "都市", "现实", "情感", "成长", "生活"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-chasing-wife",
    name: "追妻火葬场",
    channel: "女频",
    parentCategoryKeys: ["女频:267"],
    coreFantasy: "关系失衡后男方追悔，主角在重建信任中重新掌握自己的选择。",
    openingFocus: "首章让一段关系的失衡产生具体后果，并给出女主的底线。",
    commonOpenings: ["离婚当天对方才醒悟", "误会揭开后关系反转", "契约到期后对方追悔"],
    clicheTraps: ["追悔只靠台词", "女主轻易原谅", "重复误会拉扯"],
    differentiationAngles: ["让追悔有具体行动与代价", "女主有独立目标", "关系重建要过现实关"],
    typicalTags: ["追妻", "火葬场", "现言", "虐恋", "情感", "反转", "都市"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  // 幻想言情（5）
  {
    id: "f-fantasy-romance",
    name: "玄幻言情",
    channel: "女频",
    parentCategoryKeys: ["女频:248"],
    coreFantasy: "在强设定世界里情感与力量双线并进，世界规则决定两人能站多近。",
    openingFocus: "首章用一次世界规则压力迫使两人必须共同做出选择。",
    commonOpenings: ["被迫结契绑定两人", "同门对立却互相在意", "阵营敌对中暗中相护"],
    clicheTraps: ["感情脱离世界危机", "男主万能", "危机只做背景"],
    differentiationAngles: ["世界规则决定关系边界", "力量成长改变关系位置", "两人各有独立目标"],
    typicalTags: ["玄幻", "言情", "修仙", "道侣", "双强", "阵营", "情感"],
    typicalChapterWords: [2200, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-xianxia-romance",
    name: "仙侠奇缘",
    channel: "女频",
    parentCategoryKeys: ["女频:248"],
    coreFantasy: "在修行体系下选择道侣与阵营，每次境界或立场变化都重划关系边界。",
    openingFocus: "首章用一次修行规则造成的危机，让两人不得不共同承担。",
    commonOpenings: ["拜入同门后互为道侣候选", "渡劫失败被对方所救", "正邪阵营中相遇"],
    clicheTraps: ["感情线脱离修行线", "渡劫只做背景", "配角只为助攻"],
    differentiationAngles: ["把道侣写成修行选择", "境界差带来关系压力", "阵营立场各有道理"],
    typicalTags: ["仙侠", "奇缘", "道侣", "修行", "阵营", "情感", "成长"],
    typicalChapterWords: [2200, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-time-travel-romance",
    name: "穿越奇情",
    channel: "女频",
    parentCategoryKeys: ["女频:1139"],
    coreFantasy: "穿越到陌生时代后，用现代视角处理身份与情感，同时受时代约束。",
    openingFocus: "首章给出穿越后的身份处境与一个必须尽快解决的生存问题。",
    commonOpenings: ["穿越成古代庶女", "醒来成为和亲队伍一员", "穿越后被迫接受婚约"],
    clicheTraps: ["现代知识碾压时代", "时代只做背景", "感情线无现实阻力"],
    differentiationAngles: ["把时代约束写实", "现代视角带来代价而非优势", "情感选择有历史后果"],
    typicalTags: ["穿越", "古言", "情感", "身份", "时代", "权谋", "女性成长"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-superpower-romance",
    name: "异能超能",
    channel: "女频",
    parentCategoryKeys: ["女频:8"],
    coreFantasy: "在灾变与异能环境中求生，信任是稀缺资源，关系决定能走多远。",
    openingFocus: "首章用一次救不救这个人的资源选择开局。",
    commonOpenings: ["灾变当天觉醒异能", "重生回灾变前提前准备", "空间异能成为小队核心"],
    clicheTraps: ["囤货流水", "配角只会拖累", "怪物无规则"],
    differentiationAngles: ["把信任写成资源账", "让配角有独立能力", "威胁遵循可推演规则"],
    typicalTags: ["异能", "末世", "生存", "关系", "囤货", "女性成长", "危机"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-interstellar-romance",
    name: "星际言情",
    channel: "女频",
    parentCategoryKeys: ["女频:8"],
    coreFantasy: "在星际秩序中处理关系与身份，资源与立场决定两人能否同行。",
    openingFocus: "首章给出星际身份差异与一次必须共同面对的任务。",
    commonOpenings: ["随舰远征中与军官相识", "身份被调包后进入星际学院", "边境星域任务中被迫合作"],
    clicheTraps: ["星际只做背景板", "男主万能护航", "政治设定悬空"],
    differentiationAngles: ["把星际秩序写成真实约束", "关系与阵营立场绑定", "女主有独立职业目标"],
    typicalTags: ["星际", "言情", "科幻", "身份", "阵营", "关系", "成长"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  // 青春浪漫（4）
  {
    id: "f-campus",
    name: "校园",
    channel: "女频",
    parentCategoryKeys: ["女频:749"],
    coreFantasy: "在校园阶段完成成长与关系确认，学业与选择互相牵制。",
    openingFocus: "首章用具体学业或社团目标制造一次关系靠近与阻碍。",
    commonOpenings: ["开学第一天同桌初遇", "社团招新中被点名", "转学后重新开始"],
    clicheTraps: ["暧昧循环", "校园生活失真", "配角工具化"],
    differentiationAngles: ["让学业目标真实存在", "关系靠行动推进", "配角有独立成长线"],
    typicalTags: ["校园", "青春", "甜宠", "恋爱", "成长", "同桌", "轻松"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-coming-of-age",
    name: "成长",
    channel: "女频",
    parentCategoryKeys: ["女频:749"],
    coreFantasy: "以人物成长为主线，在一次次选择中确认自我与想守住的关系。",
    openingFocus: "首章给出主角可量化的短板与一个必须面对的成长节点。",
    commonOpenings: ["毕业前的关键选择", "初入职场遭遇挫折", "家庭变故后被迫独立"],
    clicheTraps: ["成长只靠旁白总结", "目标中途消失", "阻碍只靠他人使坏"],
    differentiationAngles: ["把成长写成可验证的行动", "每次进步都带来新问题", "关系随成长重新排列"],
    typicalTags: ["成长", "青春", "励志", "都市", "情感", "选择", "治愈"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-healing",
    name: "治愈",
    channel: "女频",
    parentCategoryKeys: ["女频:749"],
    coreFantasy: "以低冲突的日常修复情绪，让关系在陪伴中慢慢变得可靠。",
    openingFocus: "首章给出主角的情绪缺口与一处可依靠的具体关系。",
    commonOpenings: ["搬去小镇重新开始", "接手一间小店慢慢生活", "与旧友重逢后彼此照应"],
    clicheTraps: ["冲突全靠误会制造", "治愈只靠台词", "配角只做情绪工具"],
    differentiationAngles: ["用具体生活细节推进情绪", "让每个角色有自己的难题", "修复过程有反复而非直线"],
    typicalTags: ["治愈", "温情", "日常", "青春", "陪伴", "成长", "轻松"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-secret-crush",
    name: "暗恋",
    channel: "女频",
    parentCategoryKeys: ["女频:749"],
    coreFantasy: "从单向情感出发，用具体行动逐步完成关系确认与自我成长。",
    openingFocus: "首章给出暗恋对象的明确印象与一次被迫靠近的契机。",
    commonOpenings: ["同桌多年未曾说出口", "社团里默默关注对方", "重逢后发现对方也记得"],
    clicheTraps: ["暗恋只靠心理描写", "迟迟不行动", "配角强行搅局"],
    differentiationAngles: ["让暗恋落到具体行动", "主角有自己的成长目标", "关系推进有真实成本"],
    typicalTags: ["暗恋", "青春", "甜宠", "校园", "单向情感", "成长", "治愈"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [1, 3],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  // 悬疑推理（3）
  {
    id: "f-female-mystery",
    name: "女性悬疑",
    channel: "女频",
    parentCategoryKeys: ["女频:747"],
    coreFantasy: "从亲密关系的疑点切入案件，每排除一个嫌疑人都动摇一段关系。",
    openingFocus: "首章让一段亲密关系产生可信疑点，并给出第一份证据。",
    commonOpenings: ["伴侣突然失踪", "旧案重启后发现熟人涉案", "收到匿名证据"],
    clicheTraps: ["恋爱遮蔽案件因果", "证据凭空出现", "反派动机单薄"],
    differentiationAngles: ["案件因果优先", "关系疑点有证据支撑", "真相改变关系格局"],
    typicalTags: ["女性悬疑", "悬疑", "推理", "关系", "探案", "反转", "都市"],
    typicalChapterWords: [2000, 3000],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-republican-mystery",
    name: "民国悬疑",
    channel: "女频",
    parentCategoryKeys: ["女频:1017"],
    coreFantasy: "在民国时代背景下追查案件与身份谜团，立场与情感都被时局牵动。",
    openingFocus: "首章让一次时代危机直接改变一段关系或调查方向。",
    commonOpenings: ["接手一桩牵扯家族的旧案", "留学归国后发现身份被冒用", "战乱中寻找失踪的亲人"],
    clicheTraps: ["时代只做服化道", "立场脸谱化", "悬疑靠巧合解开"],
    differentiationAngles: ["把时代限制写进案情", "立场各有代价", "线索可回溯且受时局影响"],
    typicalTags: ["民国", "悬疑", "身份", "案件", "时代", "情感", "家国"],
    typicalChapterWords: [2200, 3200],
    firstPayoffWindow: [3, 5],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
  {
    id: "f-mystery-romance",
    name: "推理言情",
    channel: "女频",
    parentCategoryKeys: ["女频:539"],
    coreFantasy: "推理线与情感线并行推进，每查一层都可能让亲近的人变成嫌疑人。",
    openingFocus: "首章先给异常证据，再让主角做一次涉及亲近关系的选择。",
    commonOpenings: ["身边人行为突然异常", "收到一件旧物牵出往事", "搬进新家后接连出事"],
    clicheTraps: ["反转只靠隐瞒信息", "配角口述真相", "规则随时改"],
    differentiationAngles: ["所有反转前置线索", "调查伤及关系", "真相改变人物立场"],
    typicalTags: ["推理", "言情", "悬疑", "情感", "探案", "反转", "日常"],
    typicalChapterWords: [2000, 2800],
    firstPayoffWindow: [2, 4],
    source: "人工维护",
    updatedAt: "2026-09-08",
  },
];
